nexxtway/react-rainbow

.stylelintignore, .stylelintrc.json, package.json, yarn.lock
=> feat: setup stylelint

src/components/Badge/styles.css, src/components/Badge/styles.scss, src/components/ProgressBar/__test__/__snapshots__/progressBar.spec.js.snap, src/components/ProgressBar/__test__/progressBar.spec.js, src/components/ProgressBar/index.js, src/components/ProgressBar/styles.css, src/components/ProgressBar/styles.scss, src/styles/colors.scss
=> feat: impement progress bar

src/components/Application/styles/colors.css, src/components/Application/styles/colors.scss, src/components/Application/styles/rainbow-styles.css, src/components/Application/styles/rainbow-styles.scss, src/components/AssistiveText/index.js, src/components/Avatar/Readme.md, src/components/Spinner/index.js
=> refactor: avatar examples

src/components/Button/readme.md
=> refactor: button examples

src/components/ProgressBar/Readme.md
=> refactor: progressbar examples

src/components/MenuDivider/readme.md, src/components/MenuItem/readme.md
=> refactor: menuItem, menuDivider examples

integration/specs/buttonMenu-1.spec.js, src/components/ButtonMenu/index.js, src/components/MenuItem/index.js, src/components/MenuItem/styles.css, src/components/MenuItem/styles.scss
=> fix: fixed focus when hover an item

src/components/Application/styles/colors.css, src/components/Application/styles/flex.css, src/components/Application/styles/flex.scss, src/components/Application/styles/rainbow-styles.css, src/components/Button/styles.css, src/components/Input/Readme.md, src/components/Input/styles.css, src/components/Input/styles.scss, src/styles/colors.scss
=> Refactor input examples

integration/specs/buttonMenu-1.spec.js, integration/specs/verticalNavigation-11.spec.js, src/components/VerticalItem/__test__/icon.spec.js, src/components/VerticalItem/__test__/notification.spec.js, src/components/VerticalItem/__test__/verticalItem.spec.js, src/components/VerticalItem/icon.js, src/components/VerticalItem/index.js, src/components/VerticalItem/notification.js, src/components/VerticalItem/readme.md, src/components/VerticalItem/styles.css, src/components/VerticalItem/styles.scss, src/components/VerticalNavigation/__test__/verticalNavigation.spec.js
=> feat: VerticalItem implementation.

src/components/Application/readme.md, src/components/Card/Readme.md
=> refactor: application example

src/components/VerticalItem/styles.css, src/components/VerticalItem/styles.scss
=> style: changing styles.

src/components/ButtonIcon/readme.md, src/components/ButtonIcon/styles.css, src/components/ButtonIcon/styles.scss
=> refactor: buttonIcon examples

src/components/ButtonGroup/Readme.md
=> refactor: buttonGroup examples

src/components/Input/styles.css, src/components/Input/styles.scss, src/components/VerticalNavigation/styles.css, src/components/VerticalSectionOverflow/styles.css
=> fix: input styles when has error and icon on the left

src/components/ButtonIcon/styles.css, src/components/ButtonIcon/styles.scss, src/components/Card/Readme.md, src/components/Card/__test__/__snapshots__/card.spec.js.snap, src/components/Card/__test__/actions.spec.js, src/components/Card/__test__/header.spec.js, src/components/Card/__test__/headerTitle.spec.js, src/components/Card/actions.js, src/components/Card/header.js, src/components/Card/headerIcon.js, src/components/Card/headerTitle.js, src/components/Card/index.js, src/components/Card/styles.css, src/components/Card/styles.scss
=> frefactor: card component

integration/specs/buttonMenu-5.spec.js, src/components/Application/readme.md, src/components/ButtonMenu/readme.md
=> refactor: buttonMenu examples

src/components/MenuDivider/readme.md, src/components/MenuItem/readme.md
=> refactor: menuItem examples

src/components/Avatar/index.js, src/components/Badge/index.js, src/components/Button/index.js, src/components/ButtonGroup/index.js, src/components/ButtonIcon/index.js, src/components/ButtonMenu/index.js, src/components/Card/index.js, src/components/Input/index.js, src/components/MenuItem/index.js, src/components/Spinner/index.js, src/components/VerticalItem/index.js
=> docs: proptype description

.stylelintrc.json, src/components/VerticalItem/styles.css, src/components/VerticalItem/styles.scss
=> refactor: verticalItem styles.

library/pages/components/CodeEditor/header.js, library/styleguideComponents/CopyToClipboard/index.js, library/styleguideComponents/Editor/header.js, library/styleguideComponents/Editor/index.js, library/styleguideComponents/Pathline/index.js
=> feat: implement copy-to-clipboard component

README.md, library/pages/usage.md
=> fix: change CodeSandbox link

src/components/CheckboxGroup/Readme.md, src/components/CheckboxGroup/__test__/checkbox.spec.js, src/components/CheckboxGroup/__test__/checkboxGroup.spec.js, src/components/CheckboxGroup/__test__/checkboxList.spec.js, src/components/CheckboxGroup/checkbox.js, src/components/CheckboxGroup/checkboxList.js, src/components/CheckboxGroup/index.js, src/components/CheckboxGroup/readme.md, src/components/CheckboxGroup/styles.css, src/components/CheckboxGroup/styles.scss, src/styles/border-radius.scss
=> feat: implement checkbox-group component

library/styleguideComponents/Pathline/index.js, src/components/Input/index.js, src/components/MenuItem/index.js, src/components/MenuItem/styles.css, src/components/MenuItem/styles.scss, src/components/RadioGroup/__test__/radio.spec.js, src/components/RadioGroup/__test__/radioGroup.spec.js, src/components/RadioGroup/__test__/radioItems.spec.js, src/components/RadioGroup/index.js, src/components/RadioGroup/radio.js, src/components/RadioGroup/radioItems.js, src/components/RadioGroup/readme.md, src/components/RadioGroup/styles.css, src/components/RadioGroup/styles.scss
=> feat: Implement RadioGroup component.

library/styleguideComponents/ComponentsList/index.js
=> style: change to compact verticalNavigation

library/pages/components/CodeEditor/index.js, src/components/CheckboxGroup/index.js, src/components/CheckboxGroup/readme.md, src/components/CheckboxGroup/styles.css, src/components/CheckboxGroup/styles.scss, src/components/CheckboxToggle/readme.md, src/components/RadioGroup/index.js, src/components/RadioGroup/readme.md, src/components/RadioGroup/styles.css, src/components/RadioGroup/styles.scss, src/components/Select/index.js
=> docs: add description to radioGroup and checkboxGroup component

src/components/CheckboxGroup/index.js
=> docs: add description to the checkboxGroup properties

src/components/Avatar/index.js, src/components/Button/index.js, src/components/ButtonMenu/index.js, src/components/CheckboxGroup/index.js, src/components/CheckboxToggle/index.js, src/components/Input/index.js, src/components/MenuItem/index.js, src/components/RadioGroup/index.js, src/components/Select/index.js, src/components/Textarea/index.js, src/components/VerticalItem/index.js, src/components/VerticalSection/index.js, src/components/VerticalSectionOverflow/index.js
=> docs: review properties description

src/components/Select/index.js, src/components/Select/styles.css, src/components/Select/styles.scss
=> refactor: fix style in select component

library/styleguideComponents/SectionHeading/styles.css, library/styleguideComponents/Wrapper/index.js, library/styleguideComponents/Wrapper/styles.css, src/components/Application/readme.md
=> style: font-family lato to library

src/components/VerticalItem/index.js, src/components/VerticalItem/styles.css, src/components/VerticalItem/styles.scss, src/components/VerticalNavigation/__test__/verticalNavigation.spec.js, src/components/VerticalSectionOverflow/context.js, src/components/VerticalSectionOverflow/index.js, src/components/VerticalSectionOverflow/styles.css, src/components/VerticalSectionOverflow/styles.scss
=> fix: fixed keyboard navigation in VerticalSectionOverflow

src/components/CheckboxGroup/checkbox.js, src/components/CheckboxGroup/index.js, src/components/CheckboxGroup/styles.css, src/components/CheckboxGroup/styles.scss, src/components/CheckboxToggle/styles.css, src/components/CheckboxToggle/styles.scss, src/components/RadioGroup/__test__/radio.spec.js, src/components/RadioGroup/index.js, src/components/RadioGroup/radio.js, src/components/RadioGroup/styles.css, src/components/RadioGroup/styles.scss, src/components/Select/index.js, src/components/Select/readme.md, src/components/Select/styles.css, src/components/Select/styles.scss, src/components/Textarea/Readme.md, src/components/Textarea/index.js, src/components/Textarea/styles.css, src/components/Textarea/styles.scss
=> style: fix examples in select component

integration/specs/input-1.spec.js, src/components/Input/__test__/input.spec.js, src/components/Input/index.js, src/components/Input/pageObject/index.js, src/components/Input/readme.md, src/components/Input/styles.css, src/components/Input/styles.scss
=> test: Integration tests for the input.

src/components/Input/index.js
=> feat: Adding click, focus and blur methods to the Input component.

integration/specs/select-1.spec.js, src/components/Select/index.js, src/components/Select/pageObject/index.js, src/components/Select/readme.md
=> test: add integration test in select component

integration/specs/checkboxToggle-1.spec.js, src/components/CheckboxToggle/index.js, src/components/CheckboxToggle/pageObject/index.js, src/components/CheckboxToggle/readme.md
=> Checkbox toggle integration tests

integration/specs/buttonMenu-1.spec.js, integration/specs/checkboxGroup1.spec.js, src/components/CheckboxGroup/index.js, src/components/CheckboxGroup/pageObject/index.js, src/components/CheckboxGroup/readme.md
=> feat: implement page object and integration tests for checkbox group

src/components/CheckboxToggle/index.js, src/components/CheckboxToggle/styles.css, src/components/CheckboxToggle/styles.scss
=> feat: Add click, focus and blur methods to the CheckboxToggle component.

src/components/Textarea/index.js
=> feat: Add the click, focus and blur methods to the textArea component

src/components/Button/index.js, src/components/Input/index.js, src/components/Select/index.js
=> feat: Add the click, focus and blur methods to the select component

library/styleguideComponents/ComponentsList/index.js, src/components/VerticalItem/styles.scss, src/components/VerticalSectionOverflow/description.js, src/components/VerticalSectionOverflow/index.js, src/components/VerticalSectionOverflow/styles.css, src/components/VerticalSectionOverflow/styles.scss
=> fix: Fix verticalNavigation of the library.

src/components/VerticalItem/index.js, src/components/VerticalItem/styles.css, src/components/VerticalItem/styles.scss, src/components/VerticalSection/styles.css, src/components/VerticalSection/styles.scss, src/components/VerticalSectionOverflow/styles.css, src/components/VerticalSectionOverflow/styles.scss
=> fix: fixed truncate labels in VerticalNavigation

integration/constants.js, integration/specs/buttonMenu-1.spec.js, integration/specs/buttonMenu-7.spec.js, integration/specs/checkboxGroup-1.spec.js, integration/specs/modal-1.spec.js, integration/specs/modal-3.spec.js, integration/specs/radioGroup-1.spec.js, integration/specs/tabset-1.spec.js, integration/specs/verticalNavigation-11.spec.js
=> fix: added constants file for integration tests

library/styleguideComponents/ReactComponent/index.js
=> fix: change interactive example icon.

src/components/Notification/styles.css, src/components/Notification/styles.scss
=> fix: style in Notification when it's empty.

library/styleguideComponents/ReactComponent/index.js, library/styleguideComponents/SectionHeading/styles.css, library/styleguideComponents/SectionRenderer/index.js, styleguide.config.js
=> fix: padding right and left in Overview section.

library/styleguideComponents/ReactComponent/index.js
=> fix: white space on top of the accordion section documentation.

integration/specs/modal-1.spec.js, integration/specs/modal-3.spec.js, src/components/Modal/__test__/modal.spec.js, src/components/Modal/index.js, src/components/Modal/pageObject/index.js, src/components/Modal/styles.css, src/components/Modal/styles.scss, tutorials/modal.md
=> Change modal animation

library/styleguideComponents/CodeEditorButton/index.js, library/styleguideComponents/ToolbarButton/index.js, src/components/Button/__test__/button.spec.js, src/components/Button/index.js, src/components/Button/readme.md
=> fix: changing the button default variant to neutral.

src/components/Slider/__test__/label.spec.js, src/components/Slider/__test__/slider.a11y.spec.js, src/components/Slider/__test__/slider.spec.js, src/components/Slider/index.js, src/components/Slider/label.js, src/components/Slider/readme.md, src/components/Slider/style.css, src/components/Slider/style.scss
=> Implement slider

library/styleguideComponents/CopyToClipboard/index.js
=> refactor: change CopyToClipboard size in library

src/components/Button/styles.css, src/components/Button/styles.scss
=> style: fix the button disabled style when hover

src/components/Input/__test__/input.spec.js, src/components/Input/index.js, src/components/Input/inputCheckbox/__test__/input-a11y.spec.js, src/components/Input/inputCheckbox/__test__/input.spec.js, src/components/Input/inputCheckbox/__test__/label.spec.js, src/components/Input/inputCheckbox/index.js, src/components/Input/inputCheckbox/label.js, src/components/Input/inputCheckbox/styles.css, src/components/Input/inputCheckbox/styles.scss, src/components/Input/readme.md
=> fix: fix input type checkbox

src/components/ProgressIndicator/index.js
=> docs: fix property description in progressIndicator

src/components/AvatarMenu/__test__/avatarButton.spec.js, src/components/AvatarMenu/__test__/rightArrow.spec.js, src/components/AvatarMenu/avatarButton.js, src/components/AvatarMenu/pageObject/index.js, src/components/AvatarMenu/rightArrow.js, src/components/AvatarMenu/styles.css, src/components/AvatarMenu/styles.scss, src/components/PrimitiveMenu/index.js
=> style: add transition (when hover) and arrow to AvatarMenu component

src/components/CheckboxToggle/__test__/checkboxToggle.spec.js, src/components/CheckboxToggle/index.js, src/components/Input/index.js, src/components/Input/inputBase/index.js, src/components/Input/inputCheckbox/index.js, src/components/Input/inputRadio/index.js, src/components/RadioGroup/index.js, src/components/Select/index.js, src/components/Slider/index.js
=> Add prop name to imputable components

src/components/Input/index.js, src/components/Input/inputBase/index.js
=> feat: add autocomplete prop to input

library/styleguideComponents/ReactComponent/description.js, library/styleguideComponents/ReactComponent/descriptionLink.js, library/styleguideComponents/ReactComponent/index.js, library/styleguideComponents/ReactComponent/styles.css, src/components/Chart/index.js
=> docs: add link to Chart.js in description of the chart component

src/components/Card/styles.css, src/components/Card/styles.scss
=> style: Carousel component should not have a shadow when inside Card

integration/specs/modal-11.spec.js, src/components/Card/styles.css, src/components/Card/styles.scss, src/components/Modal/readme.md
=> fix: change the last modal example

src/components/Button/styles.css, src/components/ButtonIcon/styles.css, src/components/Card/styles.css, src/components/Card/styles.scss, src/styles/shadows.scss
=> style: the card component should have more shadow when hover

library/styleguideComponents/ReactComponent/Utils/index.js, library/styleguideComponents/ReactComponent/Utils/styles.css
=> style: fixing the exampleCard in utility section.

src/components/Table/__test__/table.spec.js, src/components/Table/head/__test__/head.spec.js, src/components/Table/head/__test__/header.spec.js, src/components/Table/head/header.js, src/components/Table/head/index.js, src/components/Table/index.js
=> test: added unit testing for the table and table-header

library/pages/Designs/RainbowComponents/index.js
=> fix: fix typo in design

examples/create-react-app/src/pages/Admin/header.js, library/styleguideComponents/ExperienceExampleCards/styles.css, src/components/Button/styles.css, src/components/Button/styles.scss, src/components/Slider/style.css, src/components/Slider/style.scss
=> style: add effect to the Slider component and button component

src/components/Table/body/styles.css, src/components/Table/body/styles.scss
=> feat: implement hoverable rows

src/components/CheckboxGroup/__test__/checkboxGroup.spec.js, src/components/CheckboxGroup/index.js, src/components/Input/index.js, src/components/Input/inputCheckbox/index.js
=> fix: the proptype of the prop value should accept a string in CheckboxGroup

src/components/AvatarMenu/index.js, src/components/ButtonMenu/index.js, src/components/PrimitiveMenu/__test__/primitiveMenu.spec.js, src/components/PrimitiveMenu/index.js, src/components/PrimitiveMenu/styles.css, src/components/PrimitiveMenu/styles.scss
=> fix: fix menuAlignment description in ButtonMenu and AvatarMenu and add new class in PrimitiveMenu

src/components/Input/inputBase/styles.css, src/components/Input/inputBase/styles.scss
=> style: fix input type=date, type=time styles in iOS

src/components/Badge/styles.css, src/components/Badge/styles.scss, src/components/CarouselCard/styles.css, src/components/CarouselCard/styles.scss, src/components/CarouselImage/styles.css, src/components/CarouselImage/styles.scss
=> style: fix styles on carousel and badge components

src/components/Tab/index.js, src/components/Tabset/__test__/tabset.spec.js, src/components/Tabset/index.js, src/components/Tabset/styles.css, src/components/Tabset/styles.scss, src/components/Tabset/utils.js
=> feat: fix tabset on desktop

library/styleguideComponents/Pathline/index.js, library/styleguideComponents/ReactComponent/index.js
=> fix: fix import component

src/components/MenuItem/index.js
=> docs: fix typo in prop description in the MenuItem component

src/components/Calendar/__test__/calendar.spec.js, src/components/Calendar/helpers/index.js, src/components/Calendar/helpers/normalizeDate.js, src/components/Calendar/index.js, src/components/Lookup/options/index.js
=> fix: normalize value

.circleci/config.yml, package.json, scripts/publish-canary.js, yarn.lock
The canary version use the commit sha1 like: `1.2.0-canary.{sha1}`
=> chore: create a canary release in NPM for each commit merged in master

src/components/PrimitiveMenu/styles.css, src/components/PrimitiveMenu/styles.scss
fix: #708
- Fix ButtonIcon styles when ButtonMenu is open.
[ x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/90milesbridge/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
=> styles: fix styles in buttonMenu when open

src/components/CheckboxToggle/styles.css, src/components/CheckboxToggle/styles.scss, src/components/Input/inputRadio/styles.css, src/components/Input/inputRadio/styles.scss, src/components/RadioGroup/styles.css, src/components/RadioGroup/styles.scss
fix: #560 
- Add effect to the RadioGroup component.
- Add effect to the Input type: radio component.
- Add effect to the CheckboxToggle component.
=> style: add effect to the CheckboxToogle, RadioGroup and Input type: radio

src/components/Lookup/index.js
fix: #738 
- stop propagation when press esc key 
=> fix: stop propagation when press esc key

src/components/Lookup/readme.md
=> docs: fix lookup example icon

src/components/Column/index.js, src/components/Column/readme.md
=> docs: add Column example with width

src/components/Input/inputRadio/styles.css, src/components/Input/inputRadio/styles.scss, src/components/RadioGroup/styles.css, src/components/RadioGroup/styles.scss
- Fix Input type: radio and RadioGroup styles
=> styles: fix radio styles

.prettierignore, src/components/CheckboxGroup/styles.css, src/components/CheckboxGroup/styles.scss, src/components/CheckboxToggle/styles.css, src/components/CheckboxToggle/styles.scss, src/components/Input/inputCheckbox/styles.css, src/components/Input/inputCheckbox/styles.scss, src/components/Input/inputRadio/styles.css, src/components/Input/inputRadio/styles.scss, src/components/RadioGroup/styles.css, src/components/RadioGroup/styles.scss, src/components/Table/body/styles.css, src/components/Table/body/styles.scss
- Add .prettierignore file.
- Fix some styles in checkbox.
- Correct prettier fixes in .scss
=> docs: add .prettierignore and fix some details

integration/specs/Modal/modal-11.spec.js, src/components/Lookup/__test__/lookup.spec.js, src/components/Lookup/index.js, src/components/Lookup/styles.css, src/components/Lookup/styles.scss, src/components/Modal/readme.md
fix: #743 
- Add Lookup to the Modal redux example.
=> docs: add-lookup-modal-redux-example

src/components/Table/body/__test__/row.spec.js, src/components/Table/body/row.js
fix: #751 
- access data in Table with dot notation in field
=> feat: access data with dot notation in field

src/components/Column/index.js, src/components/Input/inputRadio/styles.css, src/components/Lookup/styles.css, src/components/PrimitiveMenu/styles.css, src/components/RadioGroup/styles.css, src/components/Table/__test__/table.spec.js, src/components/Table/body/__test__/row.spec.js, src/components/Table/body/row.js, src/components/Table/body/styles.css, src/components/Table/body/styles.scss, src/components/Table/head/__test__/header.spec.js, src/components/Table/head/header.js, src/components/Table/head/styles.css, src/components/Table/helpers/columns/__test__/getColumns.spec.js, src/components/Table/helpers/columns/getColumns.js, src/components/Table/helpers/resizer/__tests__/getTableWidth.spec.js, src/components/Table/helpers/resizer/getColumnWidthFromDef.js, src/components/Table/helpers/resizer/getTableWidth.js, src/components/Table/helpers/resizer/getUpdatedColumns.js, src/components/Table/helpers/resizer/index.js, src/components/Table/index.js
fix: #746 
-  fix table widths computation and add possibility to pass width props as strings
=> fix: fix table widths computation

src/components/Table/body/row.js, src/components/Table/helpers/rows/__test__/computeUniqueRowKey.spec.js, src/components/Table/helpers/rows/computeUniqueRowKey.js, src/components/Table/helpers/rows/getFieldValue.js, src/components/Table/helpers/rows/index.js
fix: #753 
- add dot notation to keyField
=> fix: add dot notation to keyField

package.json
=> chore: update to 1.3.0 version

integration/specs/Modal/modal-11.spec.js, src/components/Lookup/index.js, src/components/Lookup/options/index.js, src/components/Lookup/options/menuItem.js, src/components/Modal/readme.md
fix: #755 
- fix onChange value when click option
=> fix: fix onChange value when click option

package.json
=> chore: update to v1.3.1

integration/RadioButtonGroup/radioButtonGroup-1.spec.js, src/components/RadioButtonGroup/__test__/buttonItems.spec.js, src/components/RadioButtonGroup/__test__/radioButton.spec.js, src/components/RadioButtonGroup/__test__/radioButtonGroup.a11y.spec.js, src/components/RadioButtonGroup/__test__/radioButtonGroup.spec.js, src/components/RadioButtonGroup/buttonItems.js, src/components/RadioButtonGroup/index.js, src/components/RadioButtonGroup/pageObject/index.js, src/components/RadioButtonGroup/pageObject/radioButton.js, src/components/RadioButtonGroup/radioButton.js, src/components/RadioButtonGroup/readme.md, src/components/RadioButtonGroup/styles.css, src/components/RadioButtonGroup/styles.scss, tutorials/RadioButtonGroup.md
fix: #585
- implement radiobuttongroup component
=> feat: implement radiobutton group component

src/components/RadioButtonGroup/styles.css, src/components/RadioButtonGroup/styles.scss
- Fix RadioButtonGroup styles in mobile
=> styles: fix RadioButtonGroup styles in mobile

src/components/Table/readme.md
=> docs: add keyfield to the Table examples

src/components/DatePicker/__test__/datePicker.spec.js, src/components/DatePicker/index.js, src/components/TimePicker/__test__/timePicker.spec.js, src/components/TimePicker/__test__/timeSelect.spec.js, src/components/TimePicker/index.js
fix: #779 #780 
- change onBlur and onFocus events in DatePicker and TimePicker
=> fix: change onBlur and onFocus events in DatePicker and TimePicker

src/components/Lookup/index.js
=> docs: fix lookup icon prop description

src/components/RadioButtonGroup/styles.css, src/components/RadioButtonGroup/styles.scss, src/components/Tab/styles.css, src/components/Tab/styles.scss
fix: #785 
- change RadioButtonGroup styles
- change Tab styles
=> styles: fix RadioButtonGroup and Tab styles

index.js
=> feat: import RadioButtonGroup in the root index

.circleci/config.yml
=> fix: update config.yml

src/components/ActivityTimeline/index.js, src/components/ActivityTimeline/styles.css, src/components/ActivityTimeline/styles.scss, src/components/TimelineMarker/styles.css, src/components/TimelineMarker/styles.scss
=> styles: fix activity-timeline container styles

.circleci/config.yml, library/exampleComponents/Icons/userFirstPost.js, library/exampleComponents/Icons/userPhoneVerified.js, src/components/Calendar/styles.css, src/components/Calendar/styles.scss
=> fix: change some calendar styles

src/components/Table/helpers/columns/__test__/getColumns.spec.js, src/components/Table/helpers/columns/getColumns.js
- change action column widht in Table
=> fix: change action column widht in Table

src/components/Table/body/__test__/cell.spec.js, src/components/Table/body/cell.js, src/components/Table/body/row.js
- pass row data and other column props passed to cell component
=> fix: pass row data and other column props passed to cell component

src/components/ActivityTimeline/readme.md, src/components/TimelineMarker/readme.md
=> fix: fix examples title

src/components/Pagination/index.js
=> docs: update Pagination documentation

src/components/WithBrowserPagination/readme.md, src/components/WithBrowserPagination/styles.css, src/components/WithBrowserPagination/styles.scss
=> styles: fix pagination styles

src/components/Table/body/cell.js
=> feat: add title to table cell

src/components/Lookup/options/styles.css, src/components/Lookup/options/styles.scss, src/components/TableWithBrowserPagination/index.js, src/components/TableWithBrowserPagination/styles.css, src/components/TableWithBrowserPagination/styles.scss
=> fix: fix styles in empty message lookup

src/components/GoogleAddressLookup/__test__/component.spec.js, src/components/GoogleAddressLookup/component.js, src/components/GoogleAddressLookup/helpers/__test__/getFormattedValue.spec.js, src/components/GoogleAddressLookup/helpers/getFormattedValue.js, src/components/GoogleAddressLookup/index.js, src/components/GoogleAddressLookup/proptypes.js
fix: 
- fix onChange to include more details about place on return value
- fix some tests
=> fix: google address lookup get place details

src/components/CheckboxGroup/styles.css, src/components/CheckboxGroup/styles.scss, src/components/RadioGroup/styles.css, src/components/RadioGroup/styles.scss
=> styles: fix radioGroup and checkboxGroup styles

src/components/TableWithBrowserPagination/styles.css, src/components/TableWithBrowserPagination/styles.scss
- Fix TableWithBrowserPagination styles
=> styles: fix tableWithBrowserPagination styles

index.js, src/components/TableWithBrowserPagination/index.js, src/libs/ResizeSensor/index.js, src/libs/debounce/index.js, src/libs/hocs/withDebounce/index.js
fix: #814 
- implement withDebounce hoc
=> feat: implement withDebounce hoc

src/components/PrimitiveMenu/index.js
=> fix: private menu click

src/components/Lookup/options/styles.css, src/components/Lookup/options/styles.scss, src/components/Lookup/styles.css, src/components/Lookup/styles.scss
=> styles: fix lookup icon styles

src/components/Calendar/helpers/__test__/formatDate.spec.js, src/components/Calendar/helpers/__test__/getFirstDayMonth.spec.js, src/components/Calendar/helpers/__test__/getFormattedMonth.spec.js, src/components/Calendar/helpers/__test__/isSameDay.spec.js, src/components/Calendar/helpers/formatDate.js, src/components/Calendar/helpers/getFirstDayMonth.js, src/components/Calendar/helpers/getFormattedMonth.js, src/components/Calendar/helpers/isSameDay.js, src/components/DatePicker/helpers/__test__/formatDate.spec.js, src/components/DatePicker/helpers/formatDate.js
fix: #858 
- fix: calendar and date picker format date
=> fix: calendar and date picker format date

src/components/Lookup/__test__/selectedValue.spec.js, src/components/Lookup/index.js, src/components/Lookup/readme.md, src/components/Lookup/selectedValue.js, src/components/Lookup/styles.css, src/components/Lookup/styles.scss
fix: #842 
- fix lookup styles when 'readOnly'
=> fix: fix lookup focus when `readOnly`

integration/specs/Lookup/lookup-1.spec.js, src/components/Lookup/pageObject/index.js, src/components/Lookup/selectedValue.js
fix: #838 
- add integration tests to lookup to check readonly and disabled states when component has value
=> test: test lookup integration

src/components/Lookup/readme.md, src/components/Lookup/styles.css, src/components/Lookup/styles.scss, src/components/ProgressIndicator/styles.css
=> docs: fix lookup interactive examples

src/components/VisualPickerOption/readme.md, src/components/VisualPickerOptionFooter/readme.md
=> docs: improve VisualPickerOption example

src/components/VisualPicker/__test__/visualPicker.spec.js, src/components/VisualPicker/index.js, src/components/VisualPicker/readme.md, src/components/VisualPickerOption/__test__/visualPickerOption.spec.js
fix: #861 
- add tests to VisualPicker component
=> test: add tests to VisualPicker component

integration/specs/VisualPicker/visualPicker-1.spec.js, integration/specs/VisualPicker/visualPicker-3.spec.js, src/components/VisualPicker/pageObject/index.js, src/components/VisualPickerOption/pageObject/index.js
fix: #861 
- add integration tests to VisualPicker component  
=> test: add integration tests to VisualPicker component

tutorials/VisualPicker.md
- add VisualPicker integration tutorial
=> test: add VisualPicker integration tutorial

.eslintrc.json, src/components/ImportRecordsFlow/helpers/getAssignFieldsData.js, src/components/ImportRecordsFlow/helpers/getDataToImport.js, src/components/ImportRecordsFlow/helpers/getFieldAssignedPreviewData.js, src/components/ImportRecordsFlow/helpers/getPreviewDataToImport.js, src/components/ImportRecordsFlow/helpers/isStepThreeNextButtonDisabled.js, src/components/ImportRecordsFlow/index.js, src/components/ImportRecordsFlow/readme.md, src/components/ImportRecordsFlow/stepFour/index.js, src/components/ImportRecordsFlow/stepThree/assignFieldModal.js, src/components/ImportRecordsFlow/stepThree/databaseFieldCell.js, src/components/ImportRecordsFlow/stepThree/fileFieldCell.js, src/components/ImportRecordsFlow/stepThree/index.js, src/components/ImportRecordsFlow/stepThree/preview.js, src/components/ImportRecordsFlow/stepThree/styles.css, src/components/ImportRecordsFlow/stepThree/styles.scss, src/components/ImportRecordsFlow/stepTwo/index.js, src/components/ImportRecordsFlow/stepTwo/styles.css, src/components/ImportRecordsFlow/stepTwo/styles.scss
- some fixes to ImportRecordsFlow component
=> fix: some fixes to ImportRecordsFlow component

assets/images/componentsThumbs/ImportRecordsFlow.svg, index.js
=> fix: add-icon-import-records-flow-component

library/pages/ComponentsPage/index.js, library/pages/ComponentsPage/styles.css, src/components/ImportRecordsFlow/index.js
- fix ExportRecordsFlow category
=> fix: exportRecordsFlow category

src/components/MenuItem/styles.css, src/components/MenuItem/styles.scss
=> styles: fix menuItem

src/components/Lookup/options/styles.css, src/components/Lookup/options/styles.scss, src/components/Picklist/index.js, src/components/Picklist/styles.css, src/components/Picklist/styles.scss, src/components/PicklistOption/styles.css, src/components/PicklistOption/styles.scss
=> styles: fix picklist

src/components/PicklistOption/index.js
- fix arrow navigation bug when option is selected
=> fix: arrow navigation bug when option is selected

src/components/ActivityTimeline/__test__/activityTimeline.spec.js, src/components/TimelineMarker/__test__/timelineMarker.spec.js
fix: #649 
- add unit test to the `ActivityTimeline` and the `TimelineMarker` components
=> test: add test to the `ActivityTimeline` and the `TimelineMarker` components

library/data/users.js, src/components/Chip/__test__/chip.spec.js, src/components/TableWithBrowserPagination/__test__/getPageItems.spec.js, src/components/TableWithBrowserPagination/__test__/options.spec.js, src/components/TableWithBrowserPagination/__test__/tableWithBrowserPagination.spec.js, src/components/TableWithBrowserPagination/helpers/getPageItems.js, src/components/TableWithBrowserPagination/index.js, src/components/TableWithBrowserPagination/options.js
fix: #818
- add test to the TableWithBrowserPagination component
=> test: add test to the TableWithBrowserPagination component

src/components/Picklist/index.js, src/components/Picklist/readme.md, src/components/Picklist/styles.css, src/components/Picklist/styles.scss, src/components/PicklistOption/index.js, src/components/PicklistOption/styles.css, src/components/PicklistOption/styles.scss
=> fix: picklist scroll

src/components/TimePicker/__test__/ampmSelect.spec.js, src/components/TimePicker/ampmSelect.js, src/components/TimePicker/helpers/__test__/getNextAmPmValue.spec.js, src/components/TimePicker/helpers/__test__/getNextHour.spec.js, src/components/TimePicker/helpers/__test__/getNextMinute.spec.js, src/components/TimePicker/helpers/__test__/getPrevHour.spec.js, src/components/TimePicker/helpers/__test__/getPrevMinute.spec.js, src/components/TimePicker/helpers/__test__/isChecked.spec.js, src/components/TimePicker/helpers/isChecked.js
- unit test to helpers and ampmSelect on TimePicker component
=> test: add unit test to helpers and ampmSelect on TimePicker component

src/components/TimePicker/__test__/timeSelect.spec.js, src/components/TimePicker/helpers/__test__/getAmPm.spec.js, src/components/TimePicker/helpers/__test__/getDefaultAmPm.spec.js, src/components/TimePicker/helpers/__test__/getHour.spec.js, src/components/TimePicker/helpers/__test__/getMinutes.spec.js, src/components/TimePicker/helpers/__test__/isNumber.spec.js, src/components/TimePicker/helpers/getAmPm.js, src/components/TimePicker/helpers/getDefaultAmPm.js, src/components/TimePicker/helpers/getHour.js, src/components/TimePicker/helpers/getMinutes.js, src/components/TimePicker/timeSelect.js
- unit test on timeSelect of the TimePicker component
=> test: add unit test on timeSelect

src/components/Picklist/readme.md, src/components/PicklistOption/index.js, src/components/PicklistOption/readme.md
=> fix: picklistOption category

src/components/PicklistOption/index.js
=> fix: category

src/components/TimePicker/__test__/timePicker.focusable.spec.js, src/components/TimePicker/__test__/timePicker.spec.js, src/components/TimePicker/helpers/__test__/getInputValue.spec.js, src/components/TimePicker/helpers/getInputValue.js, src/components/TimePicker/index.js
=> test: add unit test on timePicker component

library/pages/components/FeatureList/index.js
=> fix: getting started typo

library/pages/components/DesignDetails/index.js, library/pages/components/DesignDetails/styles.css
=> fix: design classname

src/components/Lookup/__test__/lookup.spec.js, src/components/Lookup/helpers/__test__/getInitialFocusedIndex.spec.js, src/components/Lookup/helpers/getInitialFocusedIndex.js, src/components/Lookup/index.js
fix: #789 
- add preferredSelectedOption prop to component
- add tests  
=> feat: make controllable the selected options in the Lookup component

src/components/MapMarker/styles.css, src/components/MapMarker/styles.scss
=> fix: marker styles

library/styleguideComponents/SectionHeading/index.js, library/styleguideComponents/SectionHeading/styles.css, src/components/TimePicker/styles.css, src/components/TimePicker/styles.scss
=> fix: placeholder styles for moz in TimePicker

library/styleguideComponents/SectionHeading/GithubStarsWrapper/fetchStars.js
=> fix: fetchGithubStars function

library/pages/components/FeatureList/index.js
=> fix: accessibility typo

.github/pull_request_template.md
=> fix: update template

CONTRIBUTING.md
=> fix: update CONTRIBUTING.md

.github/pull_request_template.md
=> fix: update pull_request_template.md

src/components/VisualPickerOption/styles.css, src/components/VisualPickerOption/styles.scss
fix: #985 
- Improve visualPicker styles when focus
- [ x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
=> styles: fix visualPicker when focus

src/components/TimePicker/pageObject/index.js, tutorials/TimePicker.md
fix: #968 
- Fix pageObject and Tutorials on TimePicker component.
=> fix: fix pageObject and tutorials on TimePicker component

library/styleguideComponents/StyleGuide/index.js, library/styleguideComponents/StyleGuide/styles.css, src/components/Application/readme.md, src/components/Badge/readme.md, src/components/Breadcrumb/readme.md, src/components/Breadcrumbs/readme.md, src/components/Button/readme.md, src/components/ButtonGroup/readme.md, src/components/ButtonIcon/readme.md, src/components/ButtonMenu/readme.md, src/components/Calendar/readme.md, src/components/Card/readme.md, src/components/CarouselCard/readme.md, src/components/CarouselCard/styles.css, src/components/CarouselCard/styles.scss, src/components/CarouselImage/readme.md, src/components/Chart/readme.md, src/components/CheckboxGroup/readme.md, src/components/CheckboxToggle/readme.md, src/components/Chip/readme.md, src/components/Column/readme.md, src/components/Dataset/readme.md, src/components/DatePicker/readme.md, src/components/GMap/readme.md
fix: #622 
- make responsive some components example
- [ x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
=> fix: make some examples components responsive

src/components/GoogleAddressLookup/readme.md, src/components/ImportRecordsFlow/readme.md, src/components/Input/readme.md, src/components/Lookup/readme.md, src/components/MapMarker/readme.md, src/components/MenuDivider/readme.md, src/components/MenuItem/readme.md, src/components/Modal/readme.md, src/components/Notification/readme.md, src/components/Pagination/readme.md, src/components/Picklist/readme.md, src/components/PicklistOption/readme.md, src/components/ProgressBar/readme.md, src/components/ProgressIndicator/readme.md, src/components/ProgressStep/readme.md, src/components/RadioButtonGroup/readme.md, src/components/RadioGroup/readme.md, src/components/Rating/readme.md, src/components/ReCaptcha/readme.md
fix: #622 
- Make responsive some components examples
- [ x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
=> styles: make responsive some components examples

.babelrc, package.json, scripts/copy-files.js, src/components/Badge/index.d.ts, src/components/Textarea/__test__/textarea.a11y.spec.js, src/components/index.d.ts, yarn.lock
- add ts support
- add Badge declaration file
- update babel
=> chore: add typescript support first commit

library/styleguideComponents/PropsTable/styles.css, library/styleguideComponents/ReactComponent/media-queries.css, src/components/Select/readme.md, src/components/Sidebar/readme.md, src/components/SidebarItem/readme.md, src/components/Slider/readme.md, src/components/Spinner/readme.md, src/components/Tab/readme.md, src/components/Table/readme.md, src/components/TableWithBrowserPagination/readme.md, src/components/Tabset/readme.md, src/components/Textarea/readme.md, src/components/TimePicker/readme.md, src/components/TimelineMarker/readme.md, src/components/VerticalItem/readme.md, src/components/VerticalNavigation/readme.md, src/components/VerticalSection/readme.md, src/components/VerticalSectionOverflow/readme.md, src/components/VisualPicker/readme.md, src/components/VisualPicker/styles.css, src/components/VisualPicker/styles.scss, src/components/VisualPickerOption/readme.md, src/components/VisualPickerOptionFooter/readme.md
fix: #622 
- make some components examples responsive
- [ x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
=> styles: make some components examples responsive

integration/specs/Tabset/tabset-1.spec.js
=> test: enable tabset test

library/pages/Designs/Authentication/index.js, library/pages/Designs/Chat/index.js, library/pages/Designs/ComingSoon/index.js, library/pages/Designs/CreateProfile/index.js, library/pages/Designs/NotFound404/index.js, library/pages/Designs/RainbowComponents/index.js, library/pages/Designs/SocialIconsSet/index.js, library/pages/Designs/Team/index.js
=> fix: scketch url

src/components/ProgressIndicator/__test__/progressIndicator.a11y.spec.js
#962 
- Add accessibility test on ProgressIndicator component
=> test: add accessibility test on ProgressIndicator component

src/components/ProgressCircular/__test__/progressCircular.a11y.spec.js
#962 
- Add accessibility test on ProgressCircular component.
=> test: add accessibility test on ProgressCircular component

src/components/ProgressBar/__test__/progressBar.a11y.spec.js
#962 
- Add accessibility test on ProgressBar component
=> test: add accessibility test on ProgressBar component

src/components/Notification/__test__/notification.a11y.spec.js
#962 
- Add accessibility test on Notification component
=> test: add accessibility test on Notification component

src/components/GMap/__test__/gMap.a11y.spec.js
#962 
- Add accessibility test on GMap component.
=> test: add accessibility test on GMap component

src/components/Chip/__test__/chip.a11y.spec.js
#962 
- Add accessibility test on Chip component.
=> test: add accessibility test on Chip component

src/components/Chart/__test__/chart.a11y.spec.js
#962 
- Add accessibility test on Chart component.
=> test: add accessibility test on Chart component

src/components/Sidebar/__test__/sidebar.a11y.spec.js
#962 
- Add accessibility test on Sidebar component.
=> test: add accessibility test on Sidebar component

src/components/Spinner/__test__/spinner.a11y.spec.js
#962 
- Add accessibility test on Spinner component.
=> test: add accessibility test on Spinner component

src/components/Table/__test__/table.a11y.spec.js
#962 
- Add accessibility test on Table component.
=> test: add accessibility test on Table component

src/components/TableWithBrowserPagination/__test__/tableWithBrowserPagination.a11y.spec.js
#962 
- Add accessibility test on TableWithBrowserPagination component.
=> test: add accessibility test on TableWithBrowserPagination component

src/components/VisualPicker/__test__/visualPicker.a11y.spec.js
#962 
- Add accessibility test on VisualPicker component.
=> test: add accessibility test on VisualPicker component

src/components/Modal/__test__/modal.a11y.spec.js
#962 
- Add accessibility test on Modal component.
=> test: add accessibility test on Modal component

library/styleguideComponents/ExperienceExampleCards/styles.css, src/components/DatePicker/media-queries.css, src/components/DatePicker/media-queries.scss, src/components/TimePicker/media-queries.css, src/components/TimePicker/media-queries.scss
- fix experience example card styles
=> styles: experience example card

src/components/Modal/styles.css
=> styles: modal css

src/components/Picklist/__test__/picklist.a11y.spec.js, src/components/Picklist/index.js
#962 
- Fix accessibility on Picklist component.
=> fix: fix accessibility on Picklist component

library/pages/GettingStartedPage/index.js
fix: removed excess space in the usage code example
=> fix: removed excess space in the usage example

package.json
fix: #1050 
- add styles folder to package.json files entry
=> chore: add styles folder to package.json files entry

README.md
I've shared react-rainbow components with [Bit](https://github.com/teambit/bit) into this collection:
https://bit.dev/nexxtway/react-rainbow
Now people can:
- Explore the components and play with different examples for each (live demo).
- Install individual components as packages with npm/yarn.
- See the bundle size of each component and filter components by dependencies. 
- Import components into their own projects and develop them right there.
I can hand over ownership (yoshuakuttler@gmail.com) or/and help maintain it if you prefer :)
Cheers
=> chore: update README with Components live demo

src/components/MapMarker/icon.js, src/components/MapMarker/styled/iconContainer.js
=> styles: fix MapMarker icon styles

src/components/DateTimePicker/pickerModal.js
fix: #
- fix issue with 'am/pm' when value change
=> fix: fix issue with AM/PM selector when value change

integration/specs/DateTimePicker/datetimepicker-1.spec.js, integration/specs/DateTimePicker/datetimepicker-9.spec.js, src/components/DateTimePicker/index.js, src/components/DateTimePicker/pageObject/index.js, src/components/DateTimePicker/pageObject/pageTimeSelect.js, src/components/DateTimePicker/pickerModal.js, src/components/DateTimePicker/readme.md, tutorials/DateTimePicker.md
fix: #970 
- add integration tests to DateTimePicker  component
=> test: add integration tests to DateTimePicker component

src/components/ButtonMenu/readme.md
=> fix: fix ButtonMenu example

src/components/VerticalItem/__test__/verticalItem.spec.js, src/components/VerticalItem/index.js, src/components/VerticalItem/itemContent.js, src/components/VerticalItem/styled/button.js, src/components/VerticalNavigation/__test__/verticalNavigation.spec.js
fix: #876
- Remove javascript:void(0) on VerticalItem component.
=> review: remove javascript:void(0) on VerticalItem component

library/pages/ComponentsPage/index.js, library/pages/ComponentsPage/styles.css, library/pages/Designs/styles.css, library/pages/ExperienceExamplesPage/styles.css, library/pages/GettingStartedPage/index.js, library/pages/GettingStartedPage/styles.css, library/pages/components/CarbonAds/styles.css, library/pages/components/DesignDetails/index.js, library/pages/components/DesignDetails/media-queries.css, library/pages/components/DesignDetails/styles.css, library/pages/components/FeatureList/styles.css
=> styles: add carbon in some pages

src/components/CarouselCard/styled/container.js, src/components/CarouselCard/styled/imagesUl.js, src/components/CarouselImage/__test__/carouselImage.spec.js, src/components/CarouselImage/index.js, src/components/CarouselImage/styled/innerContainer.js
fix: #1136 
- Add unit test to the CarouselImage when href prop is passed and fix some styles when active and focus.
=> test: add unit test to the CarouselImage when href prop is passed

CONTRIBUTING.md, package.json, src/components/ActivityTimeline/readme.md
=> chore: adding support for volta

src/components/Input/styled/input.js, yarn.lock
fix: #1165
- Fix input styles when getting focus clicking in the label
=> fix: input styles when getting focus clicking in the label

integration/specs/DatePicker/datepicker-1.spec.js, integration/specs/DatePicker/datepicker-13.spec.js, src/components/DatePicker/index.js, src/components/DatePicker/pageObject/index.js, src/components/DatePicker/readme.md, tutorials/DatePicker.md
fix: #647 
- Add integration test on DatePicker component
=> test: add integration test on DatePicker component

src/components/Avatar/styled/content.js, src/components/AvatarMenu/styled/button.js
=> styles: avatar

src/components/TimePicker/index.js, src/components/TimePicker/timeSelect.js, src/styles/helpers/color.js
=> fix: getContrastText and some fixes in TimePicker

src/components/Chip/readme.md, src/components/Chip/styled/buttonIcon.js, src/components/Chip/styled/container.js, src/components/Spinner/readme.md, src/components/Spinner/styled/spinner.js
fix: #1224 
#1172 
- Add support theme to Spinner and Chip components
=> feat: add support theme to spinner and chip components

src/components/TimePicker/index.d.ts
=> fix: add hour24 prop to TimePicker types file

src/components/AvatarGroup/__test__/avatarGroup.a11y.spec.js, src/components/AvatarGroup/__test__/avatarGroup.spec.js, src/components/AvatarGroup/__test__/avatars.spec.js, src/components/AvatarGroup/__test__/counter.spec.js, src/components/AvatarGroup/avatars.js, src/components/AvatarGroup/counter.js, src/components/AvatarGroup/helpers/__test__/abbreviateNumber.spec.js, src/components/AvatarGroup/helpers/abbreviateNumber.js, src/components/AvatarGroup/readme.md, src/styles/helpers/__test__/clamp.spec.js, src/styles/helpers/__test__/darken.spec.js, src/styles/helpers/__test__/decomposeColor.spec.js, src/styles/helpers/__test__/getContrastRatio.spec.js, src/styles/helpers/__test__/getContrastText.spec.js, src/styles/helpers/__test__/getLuminance.spec.js, src/styles/helpers/__test__/hexToRgb.spec.js, src/styles/helpers/__test__/hexToRgba.spec.js, src/styles/helpers/__test__/lighten.spec.js, src/styles/helpers/__test__/recomposeColor.spec.js, src/styles/helpers/__test__/rgbToRgba.spec.js, src/styles/helpers/__test__/rgbaToRgb.spec.js
#1253 
- Add unit tests to AvatarGroup component
- Some fixes to color functions
=> test: add unit tests to avatargroup component

library/pages/GettingStartedPage/index.js, styleguide.config.js
fix: #
- fix react version showed in installation section at getting started
=> fix: react version showed in getting started

src/components/Avatar/readme.md, src/components/Avatar/styled/container.js, src/components/Avatar/styled/content.js
fix: #1259 
- fix the text color and cursor on Avatar component when hover.
=> fix: the textColor and cursor to the Avatar when hover

src/components/Application/index.js
fix: #1258 
- Fix console errors and warnings
=> fix: console errors

integration/specs/DatePicker/datepicker-1.spec.js, library/hooks/useCachedState.js, library/styleguideComponents/Wrapper/index.js, src/components/DateTimePicker/index.js
fix: #1220 
- fix bug with the theme selected when the user `expand` or `shrink` the InteractiveExample
=> fix: the theme selected when the user expand or shrink the interactive example

library/exampleComponents/GlobalHeader/index.js, src/components/AccordionSection/styled/arrowIcon.js, src/components/AccordionSection/styled/heading.js, src/components/AccordionSection/styled/li.js, src/components/Application/index.js, src/components/Avatar/styled/container.js, src/components/Avatar/styled/content.js, src/components/AvatarMenu/readme.md, src/components/AvatarMenu/styled/button.js, src/styles/defaultTheme.js, src/styles/helpers/normalizeTheme.js
fix: #1267 
- add theme support to AccordionSection component
- add theme support to Avatar component
- add theme support to AvatarGroup component
- add theme support to AvatarMenu component
=> feat: add theme support to AccordionSection, Avatar, AvatarGroup and AvatarMenu components

src/components/RequiredAsterisk/styledAsterisk.js, src/components/Select/styled/innerContainer.js, src/components/Select/styled/label.js, src/components/Select/styled/select.js, src/components/Sidebar/readme.md, src/components/Sidebar/styled/nav.js, src/components/SidebarItem/readme.md, src/components/SidebarItem/styled/icon.js, src/components/SidebarItem/styled/label.js, src/components/SidebarItem/styled/li.js, src/components/Slider/styled/inputRange.js, src/components/Slider/styled/value.js, src/styles/colors.js, src/styles/defaultTheme.js, src/styles/helpers/normalizeTheme.js
fix: #1280
#1172 
- add theme support for RequiredAsterisk component
- add theme support for Select component
- add theme support for Sidebar component
- add theme support for Sidebaritem component
- add theme support for Slider component
=> feat: add theme support for RequiredAsterisk, Select, Sidebar, Sidebaritem and Slider components

src/components/Picklist/styled/arrowButton.js, src/components/Picklist/styled/dropdown.js, src/components/Picklist/styled/icon.js, src/components/Picklist/styled/indicator.js, src/components/Picklist/styled/input.js, src/components/PicklistOption/styled/headerLabel.js, src/components/PicklistOption/styled/icon.js, src/components/PicklistOption/styled/item.js, src/components/ProgressCircular/readme.md, src/components/ProgressCircular/styled/percentValue.js, src/components/ProgressCircular/styled/ringFill.js, src/components/ProgressCircular/styled/ringPath.js, src/components/ProgressIndicator/readme.md, src/components/ProgressIndicator/styled/indicatorBar.js
fix: #1278 
#1172 
- add theme support for Picklist component
- add theme support for PicklistOpttion component
- add theme support for ProgressCircular component
- add theme support for ProgressIndicator component
=> feat: add theme support for Picklist, PicklistOption, ProgressCircular and ProgressIndicator

README.md
=> chore: add CLA badge to readme

src/components/DateTimePicker/__test__/pickerModal.spec.js
=> fix: fixed date-time-picker test

library/pages/GettingStartedPage/index.js
- Added Volta documentation to contribution section
=> docs: added volta documentation to contribution section

src/components/ButtonMenu/readme.md, src/components/Modal/readme.md
=> docs: fix some examples

src/components/Tab/readme.md, src/components/Tab/styled/button.js, src/components/Tab/styled/container.js, src/components/Tabset/readme.md, src/components/Tabset/styled/buttonIcon.js, src/components/Tabset/styled/container.js, src/components/Textarea/styled/textarea.js, src/components/TimelineMarker/styled/columnLeft.js, src/components/TimelineMarker/styled/datetime.js, src/components/TimelineMarker/styled/description.js, src/components/TimelineMarker/styled/label.js, src/components/VisualPickerOption/index.js
fix: #1282
- add theme support for Tab component
- add theme support for Tabset component
- add theme support for Textarea component
- add theme support for TimelineMarker component
=> feat: add theme support for Tab, Tabset, Textarea and TimelineMarker components

src/components/Card/readme.md
=> docs: added new card example

src/components/DateTimePicker/__test__/pickerModal.spec.js, src/components/Lookup/options/styled/content.js, src/components/Lookup/options/styled/description.js, src/components/Lookup/options/styled/emptyMessage.js, src/components/Lookup/options/styled/headerLi.js, src/components/Lookup/options/styled/item.js, src/components/Lookup/styled/arrowButton.js, src/components/Lookup/styled/closeIcon.js, src/components/Lookup/styled/inputIcon.js, src/components/Lookup/styled/optionsMenu.js, src/components/Lookup/styled/selectedInput.js, src/components/Lookup/styled/selectedValueClearButton.js, src/components/MapMarker/styled/button.js, src/components/MapMarker/styled/icon.js, src/components/MapMarker/styled/label.js, src/components/MapMarker/styled/textContainer.js, src/components/Notification/styled/container.js, src/components/Notification/styled/description.js, src/components/Notification/styled/iconContainer.js, src/components/Notification/styled/title.js, src/components/Pagination/readme.md, src/components/Pagination/styled/button.js
fix: #1271 
- add theme support for Lookup component
- add theme support for MapMarker component
- add theme support for Notification component
- add theme support for Pagination component
=> feat: add theme support for Lookup, MapMarker, Notification and Pagination components

src/components/Table/readme.md
=> docs: added new table example

src/components/CheckboxGroup/readme.md
docs: new checkbox group implementation
=> docs: new checkbox group implementation

src/components/Chart/__test__/chart.spec.js, src/components/Chart/index.js, src/components/Chart/readme.md
docs: new chart implementation example
=> docs: new chart implementation example

library/pages/CustomizationPage/index.js
=> docs: fix typo

src/components/ReCaptcha/__tests__/wrapper.spec.js, src/components/ReCaptcha/component.js, src/components/ReCaptcha/index.js, src/components/ReCaptcha/readme.md, src/libs/hocs/withReduxForm/index.js
fix: reset recaptcha when two or more in the same page
=> fix: reset recaptcha when two or more in the same page

src/components/Drawer/__test__/drawer.a11y.spec.js, src/components/Drawer/__test__/drawer.spec.js, src/components/Drawer/__test__/header.spec.js, src/components/Drawer/header.js, src/components/Drawer/helpers/__test__/getSlideFrom.spec.js, src/components/Drawer/index.js, src/components/Drawer/pageObject/index.js, src/components/Drawer/readme.md, src/components/Drawer/styled/container.js, src/components/Drawer/styled/footer.js, src/components/Drawer/styled/title.js
fix: #1411 
- add unit tests for Drawer component
- add integration tests for Drawer component
=> test: drawer component

src/components/Drawer/readme.md, src/components/PresenceMap/readme.md
=> styles: on some examples

.circleci/config.yml
=> chore: add REACT_APP_STRIPE_APIKEY in ci conf

library/pages/ComponentsPage/index.js, library/pages/components/FeatureList/index.js, src/components/Calendar/index.js, src/components/StripeCardInput/index.js, src/components/StripeCardInput/readme.md
=> fix: component amount label

package.json, src/components/ImportRecordsFlow/__test__/footer.spec.js, src/components/ImportRecordsFlow/__test__/importRecordsFlow.spec.js, src/components/ImportRecordsFlow/stepFour/__test__/stepFour.spec.js, src/components/ImportRecordsFlow/stepOne/__test__/stepOne.spec.js, src/components/ImportRecordsFlow/stepTwo/__test__/preview.spec.js, src/components/ImportRecordsFlow/stepTwo/__test__/previewTable.spec.js, src/components/ImportRecordsFlow/stepTwo/__test__/stepTwo.spec.js, src/components/ImportRecordsFlow/stepTwo/__test__/uploadFileButton.spec.js, src/components/ImportRecordsFlow/stepTwo/preview.js, src/components/ImportRecordsFlow/stepTwo/previewTable.js, src/components/ImportRecordsFlow/stepTwo/uploadFileButton.js, yarn.lock
test: importRecordsFlow, stepOne, stepTwo and stepFour
=> test: importRecordsFlow, stepOne, stepTwo and stepFour

package.json, src/components/ImportRecordsFlow/stepThree/__test__/assignFieldModal.spec.js, src/components/ImportRecordsFlow/stepThree/__test__/assignFieldModalFooter.spec.js, src/components/ImportRecordsFlow/stepThree/__test__/assignFieldModalTitle.spec.js, src/components/ImportRecordsFlow/stepThree/__test__/databaseFieldCell.spec.js, src/components/ImportRecordsFlow/stepThree/__test__/fileFieldCell.spec.js, src/components/ImportRecordsFlow/stepThree/__test__/modifyCell.spec.js, src/components/ImportRecordsFlow/stepThree/__test__/preview.spec.js, src/components/ImportRecordsFlow/stepThree/__test__/selectedFieldsToAssign.spec.js, src/components/ImportRecordsFlow/stepThree/__test__/stepThree.spec.js, yarn.lock
test: importRecordsFlow specs stepThree
=> test: importRecordsFlow specs stepThree

src/components/MonthlyCalendar/index.d.ts, src/components/index.d.ts
fix: #1439 
- fix index.ts file in MonthlyCalendar component
=> fix: fix index.ts file in MonthlyCalendar component

src/components/ImportRecordsFlow/footer.js, src/components/ImportRecordsFlow/helpers/getStepComponent.js, src/components/ImportRecordsFlow/index.d.ts, src/components/ImportRecordsFlow/index.js, src/components/StripeCardInput/index.js
=> feat: add actionType prop to ImportRecordsFlow

src/components/ButtonGroupPicker/index.js, src/components/ButtonOption/index.js
=> fix: change components groups

src/styles/colors.js, src/styles/defaultTheme.js
=> styles: disabled colors

library/styleguideComponents/PropsTable/renderers/builders/instanceOfType.js, library/styleguideComponents/PropsTable/renderers/builders/unionTypeList.js
fix: #1502 
- fix render of intanceOf type in union props  
=> chore: fix instanceOf type in union props

src/components/ImportRecordsFlow/readme.md
=> doc: add importRecordsFlow example

library/styleguideComponents/PropsTable/bodyRows.js, library/styleguideComponents/PropsTable/styles.css
fix: #1504
- fix documentation table
=> fix: documentation Table is broken

library/styleguideComponents/Examples/index.js
=> styles: remove ;

library/pages/customization.md
fix: #1525 
- Fix console error on customize section
=> fix: fix console error on customize section

src/components/StrongPasswordInput/index.js
…tside ref
fix: update to useImperativeHandle to control ref events only from outside ref
=> fix: update to useImperativeHandle to control ref events only from outside ref

src/components/FileSelector/readme.md
=> styles: fix example

library/pages/CustomizationPage/index.js, src/styles/defaultTheme.js, src/styles/helpers/normalizeTheme.js
=> styles: add shadows

src/components/Picklist/styled/input.js, src/styles/defaultTheme.js
=> styles: fix sahdow

src/components/CodeInput/styled/index.js
fix: #1551 
- fix: styles when clicking the CodeInput and this have an error
=> fix: styles when clicking the CodeInput and this have an error

src/components/InternalDropdown/helpers/__test__/isChildRegistered.spec.js, src/components/InternalDropdown/helpers/isChildRegistered.js, src/components/InternalDropdown/helpers/searchFilter.js, src/components/InternalDropdown/index.js, src/components/InternalDropdown/readme.md, src/components/InternalDropdown/styled/index.js, src/components/Picklist/index.js, src/components/Picklist/readme.md, src/components/PicklistOption/index.js
=> feat: add input search to InternalDropdown

src/components/Picklist/readme.md, src/components/PicklistOption/readme.md
=> docs: change the examples where PicklistOption is being used to Option

src/components/Option/__test__/option.spec.js, src/components/Option/index.js
- Fix Option component and tests when multiple
=> fix: option tests failing

package.json, yarn.lock
=> chore: fix chartjs version

src/components/Avatar/styled/container.js, src/components/Avatar/styled/image.js, src/components/InternalDropdown/styled/index.js
=> fix: avatar img styles

src/components/InternalDropdown/icons/searchIcon.js, src/components/InternalDropdown/index.js, src/components/InternalDropdown/styled/index.js, src/components/PrimitiveMenu/styled/dropdown.js
=> fix: input search on internalDropdown

src/components/Avatar/styled/content.js, src/components/Avatar/styled/image.js
=> fix: max-width

README.md, library/pages/ComponentsPage/index.js, library/pages/components/FeatureList/index.js
=> docs: update components amount

library/pages/ComponentsPage/index.js
=> docs: change components amount title

src/components/Tree/styled/label.js, src/components/Tree/treeChildren.js
fix: #1668
- improve Tree component
=> fix: improve Tree component

src/components/Chip/readme.md
=> fix: chip example

library/pages/components/CodeEditor/styles.css, library/styleguideComponents/Editor/header.js, library/styleguideComponents/Editor/index.js, library/styleguideComponents/Editor/styles.css, library/styleguideComponents/Playground/styles.css
=> fix: playground styles

library/pages/ComponentsPage/index.js
=> chore: count component dynamically

src/components/Chart/index.js
- modify import in the Chart component
=> fix: modify import in the Chart component

README.md
=> chore: add code climate badge

README.md
=> fix: code climate badge

.github/ISSUE_TEMPLATE/--bug-report.md
=> chore: update bug template

.github/ISSUE_TEMPLATE/feature_request.md
=> chore: update new feature template

.github/ISSUE_TEMPLATE/discussion.md
=> chore: create discussion template

.github/ISSUE_TEMPLATE/discussion.md
=> fix: some typos

src/components/Tree/child.js, src/components/Tree/expandCollapseButton.js, src/components/Tree/styled/button.js, src/components/Tree/styled/inputCheckbox.js, src/components/Tree/styled/itemContainerLi.js, src/components/Tree/styled/label.js, src/components/Tree/styled/nodeContainer.js, src/components/Tree/styled/spinnerContainer.js
=> styles: tree

src/components/Tree/index.d.ts
=> fix: tree typescript interface

src/components/Tree/__test__/tree.spec.js, src/components/Tree/child.js, src/components/Tree/helpers/shouldSelectNode.js, src/components/Tree/index.d.ts, src/components/Tree/pageObject/node.js, src/components/Tree/styled/innerContainer.js, src/components/Tree/styled/itemContainerLi.js
=> fix: tree events

src/components/Picklist/readme.md
=> fix: picklist readme issue

src/components/Chip/index.d.ts
=> feat: add ts variant interface to chip component

src/components/Picklist/index.d.ts
=> feat: add enablesearch to ts

CONTRIBUTING.md, library/pages/GettingStartedPage/index.js, library/pages/GettingStartedPage/styles.css
=> feat: add discussion docs to the project

.github/ISSUE_TEMPLATE/idea.md
=> docs: add "idea" issue template

.github/ISSUE_TEMPLATE/idea.md
=> fix: badge on template

src/components/Lookup/styled/optionsMenu.js
=> style: add animation to the lookup component

src/components/Table/readme.md
=> docs: add the data table with custom actions and wrap description

src/components/Rating/star.js, src/components/Rating/styled/starContainer.js
=> styles: add animation to Rating component

src/components/RenderIf/index.d.ts, src/components/RenderIf/index.js, src/components/RenderIf/readme.md, src/components/index.d.ts, src/components/index.js
=> docs: renderIf component

src/components/Button/index.js
=> feat: add htmlElementRef class getter

src/components/Button/__test__/button.spec.js, src/components/Button/index.js
=> fix: htmlElementRef in Button component

integration/specs/ColorPicker/colorPicker-1.spec.js, src/components/ColorPicker/commons/saturation/index.js, src/components/ColorPicker/pageObject/index.js, src/components/ColorPicker/readme.md
fix: #1804 
- test: add integration test
- fix: change window listener to containerRef
=> test: add integration test to ColorPicker component

src/components/Avatar/readme.md
fix: #1827
- add new InteractiveExample
=> docs: add InteractiveExample on Avatar component with custom size

library/styleguideComponents/ComponentsList/index.js, package.json, yarn.lock
=> feat: add custom work form

.gitignore, library/styleguideComponents/StyleGuide/styles.css
fix: #1850
- modify twitter button styles
=> fix: the Twitter button does not work

src/components/Textarea/index.js, src/components/Textarea/styled/textareaContainer.js
=> fix: focus on Textarea

library/styleguideComponents/ReactComponent/styles.css, src/components/Input/readme.md
=> docs: add example with an initial value set in the input component

library/data/dataTableExamples.js, library/setup.js, src/components/Table/exampleData.js, src/components/Table/readme.md
=> docs: example of dynamic row action in table component

src/components/Input/readme.md
=> fix: controlled input example

src/components/Drawer/index.d.ts, src/components/Drawer/index.js, src/components/Drawer/readme.md, src/components/Drawer/styled/container.js
=> feat: add full value to the size prop on the drawer

.circleci/config.yml
=> chore: add algolia env varibales to CI

library/styleguideComponents/GlobalSearch/algoliaConnectedComponents/SearchResult/ResultItem.js, library/styleguideComponents/GlobalSearch/algoliaConnectedComponents/SearchResult/ResultItems.js, library/styleguideComponents/GlobalSearch/algoliaConnectedComponents/SearchResult/index.js, library/styleguideComponents/GlobalSearch/index.js
=> fix: close algolia results menu when select an item

src/components/Table/readme.md
=> fix: changed data in table hide header example

src/components/Table/readme.md
=> docs: changed table examples description

src/components/Table/index.js
=> docs: changed table proptypes description

src/components/Table/readme.md
=> docs: change mispellings and camelcase in table

.eslintrc.json, src/components/StripeCardInput/styled/container.js
=> style: add border error when empty

src/components/StripeCardInput/index.js
=> fix: remove events from array dependencies in StripeInput

src/components/Button/styled/button.js, src/components/ButtonIcon/styled/button.js
=> fix: shaded styles

src/components/Option/__test__/option.spec.js, src/components/Option/index.js, styleguide.config.js
=> Option component prop

src/components/Select/index.d.ts, src/components/Select/index.js, src/components/Select/styled/select.js
=> feat: added variant shaded to select component

src/components/Table/readme.md
=> docs: add info in table with inline example

src/components/InternalDropdown/__test__/internalDropdown.spec.js, src/components/InternalDropdown/index.js, src/components/Option/index.js, src/components/Option/styled/item.js, src/components/Picklist/index.js
=> feat: add onSearch prop to Picklist

src/components/Table/readme.md
Delete an unnecessary period and modify the name of the Table "listview" variant example
fix: #
-
=> docs: change name of table listview variant ex

src/components/Column/readme.md
=> docs: add description in column component

README.md, library/pages/components/FeatureList/index.js
=> fix: components amount

src/components/Column/index.js, src/components/Column/readme.md
=> docs: column component general description

src/components/Column/index.js
=> docs: typos in column comp props and methods

src/components/Input/inputBase/index.js, src/components/Input/styled/input.js
=> fix: focus styles when variant=bare

src/components/Pagination/index.js
=> docs: add general description to pagination comp

src/components/Pagination/readme.md
=> docs: add description to pagination component

src/components/Lookup/__test__/lookup.spec.js, src/components/Lookup/index.js
=> fix: hide error when loading in Lookup

src/components/InternalOverlay/hooks/useDisableScroll.js, src/components/InternalOverlay/index.d.ts, src/components/InternalOverlay/index.js
=> feat: add prop keepScrollEnabled on InternalOverlay

README.md
=> docs: add and change readme info

src/components/GoogleAddressLookup/component.js, src/components/GoogleAddressLookup/index.d.ts, src/components/GoogleAddressLookup/index.js
fix: #1993 
-add propTypes and defaultProps for variant on index.js
-pass prop variant to Component
-add propTypes and defaultProps for variant on component.js
=> feat: implement variant on GoogleAddressLookup

.circleci/config.yml
=> chore: update resource_class to medium+ in CI

src/components/Avatar/index.d.ts, src/components/AvatarMenu/avatarButton.js, src/components/AvatarMenu/index.d.ts, src/components/AvatarMenu/index.js
=> feat: implement avatarBackgroundColor prop on AvatarMenu component

integration/specs/Picklist/picklist-3.spec.js, src/components/Pagination/index.js, src/components/Picklist/index.js, src/components/Picklist/pageObject/index.js, src/libs/outsideClick/index.js
fix: #1978
- Fix unexpected close on Picklist when clicking the search input
- Add test case to this specific issue
- Fix minor lint error on Pagination
=> fix: picklist close unexpected when clicking on the search

src/components/InternalDropdown/index.js
=> fix: fix console error on Picklist

src/components/Sidebar/index.js
=> docs: add general info in sidebar component

src/components/Sidebar/readme.md
=> docs: add info to sidebar component

src/components/Sidebar/index.js
=> docs: fix typo in general info on sidebar comp

src/components/Sidebar/readme.md
=> docs: fix typo issues in sidebar examples

src/components/Table/body/styled/cellContainer.js
fix: #2055
- fix styles in Table component when variant is listview
=> fix: styles in Table component when variant is listview

src/components/Input/styled/input.js, src/components/Picklist/index.d.ts, src/components/Picklist/index.js, src/components/Picklist/readme.md, src/components/Picklist/styled/input.js
fix: #2062
- add bare variant on the Picklist component
- add new example on the Picklist component
- fix indentation problems in Input component
=> feat: add bare variant on the Picklist component

src/components/TableWithBrowserPagination/readme.md
=> docs: tablewithbrowserpagination examples doc

src/components/Chart/index.js, src/components/Chart/readme.md
fix: #2073
- Improve documentation on Chart component
-----
=> docs: improve documentation on Chart component

library/styleguideComponents/RibbonRenderer/index.js
=> feat: add Smart link

src/components/Chart/helpers/unregisterGlobalPlugins.js
=> fix: fix chart legend never showing

src/components/ProgressIndicator/index.js, src/components/ProgressIndicator/readme.md, src/components/ProgressIndicator/styled/indicatorBar.js, src/components/ProgressStep/index.js, src/components/ProgressStep/readme.md, src/components/ProgressStep/styled/label.js, src/components/ProgressStep/styled/step.js, src/components/ProgressStep/styled/stepButton.js
fix: #2046
- Improve ProgressIndicator and ProgressStep examples
- Fix label size and other styles
-----
=> fix: improve progress step docs

integration/specs/Modal/modal-11.spec.js, package.json, src/components/Modal/readme.md, src/components/MultiSelect/pageObject/index.js
fix: #2094 
- Add integration test for modals containing MultiSelect and Picklist components
=> test: add integration test to Modal with dropdown

library/pages/Designs/RainbowComponents/index.js
=> fix: sketch URL

src/components/CheckboxToggle/index.d.ts
=> feat: add ts interface to CheckboxToggle

src/components/ActivityTimeline/accordionTimeline.js, src/components/ActivityTimeline/basicTimeline.js, src/components/ActivityTimeline/index.d.ts, src/components/ActivityTimeline/index.js, src/components/ActivityTimeline/readme.md, src/components/TimelineMarker/accordionMarker.js, src/components/TimelineMarker/basicMarker.js, src/components/TimelineMarker/index.js, src/components/TimelineMarker/styled/columnLeft.js
fix: #2099 
- some code enhancements
=> fix: enhance code

scripts/search/create-searchable-content.js, scripts/search/update-searchable-index.js
=> feat: updated script search algolia

src/components/Slider/styled/label.js, src/components/Slider/styled/slider.js
=> fix: remove padding on slider

src/components/ButtonIcon/index.js, src/components/ButtonIcon/readme.md
fix: #2105
- Improve ButtonIcon documentation
=> docs: improve ButtonIcon docs

src/components/Tab/styled/button.js
=> fix: font-size on Tab component

src/components/Tab/styled/button.js, src/components/Table/body/styled/cell.js, src/components/Table/body/styled/cellContent.js, src/components/Table/head/styled/th.js, src/components/Table/styled/thead.js
=> fix: table styles

src/components/Tab/styled/button.js, src/components/Tabset/readme.md
=> fix: font size on tabset

package.json, scripts/search/algoliaInitiation.js, scripts/search/update-medium-index.js, scripts/search/update-searchable-index.js, scripts/search/update-youtube-index.js
=> feat: added script update medium index

src/components/PresenceMap/index.d.ts, src/components/Spinner/index.d.ts, src/libs/hocs/withReduxForm/index.js, src/libs/hooks/useReduxForm.js, src/libs/manageTab/index.d.ts
=> fix: add dirty to useReduxForm and withReduxForm

src/components/Slider/index.js, src/components/Slider/styled/value.js
=> fix: slider width changes when number of digits changes

integration/specs/Drawer/drawer-7.spec.js, integration/specs/Modal/modal-11.spec.js, src/components/Drawer/index.js, src/components/Drawer/readme.md, src/components/Modal/index.js
fix: #2164
Shoud also fix https://github.com/nexxtway/rainbow-modules/issues/332
- Fix Drawer closing when Esc key is pressed on Picklist
- Fix Modal closing when Esc key is pressed on Picklist
=> fix: picklist inside a drawer close drawer when pressing ESC

scripts/search/algoliaClient.js
=> fix: fixed algolia client script

src/components/Button/content.js, src/components/Table/body/cell.js
=> fix: pass index to table column component

src/components/SidebarItem/styled/label.js
=> fix: sidebar label color

src/components/Column/index.d.ts, src/components/Column/index.js, src/components/Table/body/__test__/cell.spec.js, src/components/Table/body/cell.js
=> feat: let isEdtiable to be a func that returns a bool in Table Column

src/components/Column/index.d.ts, src/components/Column/index.js, src/components/Table/body/cell.js, src/components/Table/body/row.js, src/components/Table/body/styled/cell.js
=> feat: add cellAlignment prop to Table Column

src/components/Table/head/styled/th.js, src/components/Table/readme.md, src/components/Table/styled/scrollableY.js
=> fix: divider on table

src/components/Table/styled/scrollableY.js
=> fix: remove divider when the variant is listview

src/components/MarkdownOutput/renderers/styled.js
=> fix: markdownOutput styles

src/components/MarkdownOutput/renderers/styled.js
=> fix: markdown paddings

src/components/MarkdownOutput/renderers/index.js, src/components/MarkdownOutput/renderers/styled.js
=> fix: pre tag on markdown output

src/components/MarkdownOutput/renderers/styled.js
=> fix: bold MarkdownOutput

src/components/Drawer/styled/container.js
=> fix: remove transform when visible in Drawer

src/components/Table/helpers/rows/__test__/computeUniqueRowKey.spec.js, src/components/Table/helpers/rows/computeUniqueRowKey.js
=> fix: add support for numeric values on keyField

src/components/MarkdownOutput/index.d.ts
=> fix: add variant to type declaration in MarkdownOutput

integration/specs/Lookup/lookup-1.spec.js, integration/specs/Lookup/lookup-3.spec.js, integration/specs/Lookup/lookup-5.spec.js, src/components/Lookup/__test__/lookup.spec.js, src/components/Lookup/helpers/__test__/lookupPositionResolver.spec.js, src/components/Lookup/helpers/lookupPositionResolver.js, src/components/Lookup/index.js, src/components/Lookup/options/index.js, src/components/Lookup/pageObject/index.js, src/components/Lookup/styled/optionsMenu.js
- Use InternalOverlay on Lookup dropdown
=> fix: use InternalOverlay on Lookup dropdown

src/components/Lookup/styled/arrowButton.js
fix: #2232 
-add border-radius to arrowButton.js
-change margin-top to 0.4rem
=> fix: add border radius and modify margin top on arrowButton.js

src/components/InternalTooltip/styled/index.js
=> fix: tooltip styles

integration/specs/Accordion/accordion-1.spec.js, integration/specs/Accordion/accordion-11.spec.js, integration/specs/Accordion/accordion-5.spec.js, integration/specs/Accordion/accordion-9.spec.js, src/components/Accordion/__test__/accordion.spec.js, src/components/Accordion/index.js, src/components/Accordion/readme.md, src/components/AccordionSection/index.js, src/components/AccordionSection/pageObject/index.js, src/components/AccordionSection/readme.md, src/components/AccordionSection/styled/arrowIcon.js, src/components/AccordionSection/styled/content.js, src/components/AccordionSection/styled/heading.js, src/components/AccordionSection/styled/li.js, src/components/AccordionSection/styled/span.js, src/components/AccordionSection/styled/summary.js, src/styles/borderRadius.js
- Improve Accordion styles
- Add variant prop to AccordionSection
=> fix: add accordion variant and improve styles

src/components/Tree/__test__/tree.spec.js, src/components/Tree/helpers/__test__/buildPlainListFromTree.spec.js, src/components/Tree/helpers/buildPlainListFromTree.js, src/components/Tree/index.js
- Fix crash on Tree when data is invalid
=> fix: fix Tree crash when data is invalid

src/components/TableWithBrowserPagination/index.js, src/components/TableWithBrowserPagination/styled/container.js
=> fix: tableWithBrowserPagination overflow

src/components/Tree/index.d.ts
=> fix: fix Tree declaration

integration/specs/Modal/modal-11.spec.js, src/components/Lookup/index.js, src/components/Modal/readme.md
- Close Lookup when `Esc` key is pressed
- Add integration test
=> fix: close lookup when `Esc` key is pressed

src/libs/utils/getSuffixSI.js
=> fix: remove console error

src/components/Table/body/cell.js, src/components/Table/body/styled/cell.js, src/components/Table/body/styled/cellContainer.js, src/components/Table/body/styled/cellContent.js, src/components/Table/body/styled/editableCell.js, src/components/Table/readme.md
=> fix: issues with table styles in mozilla

src/components/Table/body/styled/cellContent.js
=> fix: height on table

src/components/Input/label/labelText.js
=> fix: label input some styles

src/components/Input/label/labelText.js
Reverts nexxtway/react-rainbow#2316
=> Revert "fix: label input some styles"

src/components/Drawer/header.js
=> fix: divider on Drawer

src/components/ColorInput/__test__/colorInput.spec.js
=> test: improve test case on ColorInput component

src/components/PhoneInput/countriesDropdown/styled/index.js
=> fix: fix PhoneInput dropdown styles without Application

src/components/PhoneInput/countries.js
=> fix: fix PhoneInput styles when not using Application

src/components/PhoneInput/readme.md
=> fix: add custom country example to the input phone

integration/specs/MultiSelect/multiSelect-11.spec.js, src/components/MultiSelect/__test__/multiSelect.spec.js, src/components/MultiSelect/index.js, src/components/MultiSelect/readme.md
fix: #2287 
- Added the `enableSearch` prop to the MultiSelect component
=> feat: add `enableSearch` prop to MultiSelect component

src/components/DateTimePicker/readme.md
=> docs: add datetimepicker example

src/components/MarkdownOutput/renderers/styled.js
=> fix: fix inline code styles on list item

src/components/Select/readme.md
- Improved `Select` component docs
=> docs: improve Select examples

src/components/RadioGroup/styled/itemDescription.js
=> fix: checkbox and radio description styles

library/data/dataTableExamples.js, library/setup.js, src/components/Column/index.js, src/components/Column/readme.md, src/components/Table/head/__test__/header.spec.js, src/components/Table/head/header.js
feat: add `headerComponent` prop to the column component
-
=> feat: add `headerComponent` prop to the column component

src/components/InternalDropdown/index.d.ts, src/components/InternalDropdown/index.js, src/components/InternalDropdown/readme.md, src/components/Picklist/index.d.ts, src/components/Picklist/index.js
=> fix: add empty component prop

.circleci/config.yml, integration/specs/AvatarMenu/avatarMenu-1.spec.js, integration/specs/ButtonGroupPicker/buttonGroupPicker-1.spec.js, integration/specs/ButtonGroupPicker/buttonGroupPicker-3.spec.js, integration/specs/ButtonMenu/buttonMenu-13.spec.js, integration/specs/ButtonMenu/buttonMenu-17.spec.js, integration/specs/ButtonMenu/buttonMenu-5.spec.js, integration/specs/ButtonMenu/buttonMenu-7.spec.js, integration/specs/Calendar/calendar-1.spec.js, integration/specs/Calendar/calendar-3.spec.js, integration/specs/Calendar/calendar-5.spec.js, integration/specs/Calendar/calendar-7.spec.js, integration/specs/Calendar/calendar-9.spec.js, integration/specs/CarouselCard/carouselCard-3.spec.js, integration/specs/CarouselCard/carouselCard.spec.js, package.json, src/components/Table/head/header.js, wdio.conf.js, yarn.lock
=> fix: headerComponent prop causes a warning when no passed to Table

src/components/FileSelector/index.js
=> fix: placeholder type on fileSelector

src/components/Calendar/__test__/day.spec.js, src/components/Calendar/day.js, src/components/Calendar/singleCalendar.js, src/components/Calendar/styled/dayAdjacent.js
- Fixed keyboard navigation on disabled days
=> fix: fix keyboard navigation on disabled days

src/components/Input/label/index.d.ts, src/components/InternalDropdown/index.js, src/components/Picklist/index.js
=> fix: picklist warnings

src/components/AccordionSection/styled/summary.js
=> fix: ";" missing on accordion component

src/components/CounterInput/index.d.ts, src/components/CounterInput/index.js, src/components/CounterInput/styled/index.js
fix: #2478 
- feat: add counter input prop size
=> feat: add counter input prop size

src/components/Picklist/index.d.ts, src/components/Picklist/index.js
fix: #2480 
-  feat: add picklist prop size
=> feat: add picklist prop size

src/components/Calendar/__test__/day.spec.js, src/components/Tab/__test__/tab.spec.js, src/components/Tab/index.js, src/components/Tabset/__test__/tabset.spec.js, src/components/Tabset/index.js
=> fix: tabset for react 18

src/components/VerticalItem/index.js
=> fix: fix verticalitem icon not allowing to click item

src/components/ButtonGroupPicker/index.d.ts, src/components/ButtonGroupPicker/index.js, src/components/ButtonGroupPicker/readme.md, src/components/ButtonGroupPicker/styled/index.js, src/components/RadioButtonGroup/readme.md, src/styles/borderRadius.d.ts
fix: #2497 
-add borderRadius prop to ButtonGroupPicker component
=> feat: add borderRadius prop to ButtonGroupPicker component

library/styleguideComponents/StyleGuide/styles.css
fix: #2510 
- fix: behavior of chat and menu button of the doc
=> fix: behavior of chat and menu button of the doc

src/components/ButtonGroup/readme.md
fix: #2464 
-changing the way of calling the FontAwesome icon for making it not taking other styles
=> Fix button group when button menu as children

src/components/Chip/index.js, src/components/Chip/readme.md, src/components/Chip/styled/container.js
fix: #2501 
-feat: add borderRadius prop to Chip component
=> feat: add borderRadius prop to Chip component

src/components/CurrencyInput/index.js, src/components/DateTimePicker/readme.md, src/components/PercentInput/index.js
fix: #2521
-fix: CurrencyInput and PercentInput must open a numeric keyboard in mobile devices
-fix: taking the constants out of the function in DateTimePicker component
=> Currencyinput percentinput numeric keyboard mobile

CONTRIBUTING.md
fix: #
- fix: minor stylistic fix for docs
=> fix: minor stylistic fix for docs

src/components/Avatar/index.d.ts
=> fix: avatar backgroundColor type

src/components/ButtonMenu/index.d.ts, src/components/ButtonMenu/index.js, src/components/ButtonMenu/readme.md, src/components/PrimitiveMenu/index.js, src/components/PrimitiveMenu/styled/index.js
fix: #2568 
- feat: add borderRadius prop to ButtonMenu component
=> feat: add borderRadius prop to ButtonMenu component

src/components/ColorInput/index.js, src/components/ColorInput/styled.js
fix: #2575 
- feat: add borderRadius prop to ColorInput menu
=> feat: add borderRadius prop to ColorInput menu

src/components/Textarea/index.d.ts, src/components/Textarea/index.js
=> feat: add onKeyDown prop to textarea component

src/components/Avatar/styled/container.js, src/components/Avatar/styled/content.js
=> fix: initials styles on avatar

src/components/ImportRecordsFlow/footer.js, src/components/ImportRecordsFlow/index.d.ts, src/components/ImportRecordsFlow/index.js, src/components/ImportRecordsFlow/readme.md, src/components/ImportRecordsFlow/stepOne/index.js, src/components/ImportRecordsFlow/stepThree/assignFieldModal.js, src/components/ImportRecordsFlow/stepThree/assignFieldModalFooter.js, src/components/ImportRecordsFlow/stepThree/csvCell.js, src/components/ImportRecordsFlow/stepThree/databaseFieldCell.js, src/components/ImportRecordsFlow/stepThree/index.js, src/components/ImportRecordsFlow/stepThree/selectedFieldsToAssign.js, src/components/ImportRecordsFlow/stepThree/styled/databaseFieldCell.js, src/components/ImportRecordsFlow/stepTwo/index.js, src/components/ImportRecordsFlow/stepTwo/preview.js, src/components/ImportRecordsFlow/stepTwo/styled/fileCard.js, src/components/ImportRecordsFlow/stepTwo/styled/uploadFileLabel.js, src/components/ImportRecordsFlow/stepTwo/uploadFileButton.js
fix: #
-adding border radius prop to ImportRecordFlow component
=> feat: adding border radius prop to import record flow

src/components/Table/body/cell.js, src/components/Table/body/styled/cell.js
=> fix: padding on first column on Table

src/components/Button/styled/button.js, src/components/ButtonIcon/styled/button.js
=> feat: improve button styles

src/components/ImportRecordsFlow/stepOne/styled/optionPicker.js
=> fix: option styles

src/components/Textarea/styled/textarea.js, src/components/Textarea/styled/textareaContainer.js
=> fix: textarea with grow prop move elements around when focus

src/components/Slider/index.js
=> fix: slider to work with redux form
