nexxtway/react-rainbow

- src/components/ReCaptcha/component.js
- src/components/ReCaptcha/get-url.js
- src/components/ReCaptcha/index.js
- src/components/ReCaptcha/loader.js
- src/components/ReCaptcha/readme.md
- src/components/ReCaptcha/styles.css
- src/components/ReCaptcha/styles.scss
- src/components/ReCaptcha/wrapper.js
> feat: implement ReCaptcha component

- src/components/AvatarMenu/__test__/avatarButton.spec.js
- src/components/AvatarMenu/__test__/avatarMenu-a11y.spec.js
- src/components/AvatarMenu/__test__/avatarMenu.spec.js
- src/components/AvatarMenu/avatarButton.js
- src/components/AvatarMenu/index.js
- src/components/AvatarMenu/readme.md
- src/components/AvatarMenu/styles.css
- src/components/AvatarMenu/styles.scss
- src/styles/shadows.scss
> feat: implement the AvatarMenu component

- integration/specs/avatarMenu-1.spec.js
- integration/specs/buttonMenu-5.spec.js
- src/components/AvatarMenu/pageObject/index.js
- src/components/AvatarMenu/readme.md
- src/components/AvatarMenu/styles.css
- src/components/AvatarMenu/styles.scss
- src/styles/shadows.scss
> test: add integration test in avatarMenu component

- src/components/CarouselImage/styles.css
- src/components/Pagination/get-first-item.js
- src/components/Pagination/index.js
- src/components/Pagination/leftArrow.js
- src/components/Pagination/navigationButton.js
- src/components/Pagination/pageButtons.js
- src/components/Pagination/readme.md
- src/components/Pagination/rightArrow.js
- src/components/Pagination/styles.css
- src/components/Pagination/styles.scss
> feat: implement pagination

- src/components/Button/__test__/button.spec.js
- src/components/Button/buttonContent.js
- src/components/Button/content.js
- src/components/Button/index.js
- src/components/Button/readme.md
- src/components/Button/styles.css
- src/components/Button/styles.scss
> feat: add isLoading to the Button component

- src/components/Column/index.js
- src/components/Table/__test__/table.spec.js
- src/components/Table/body/cell.js
- src/components/Table/body/index.js
- src/components/Table/body/row.js
- src/components/Table/body/styles.css
- src/components/Table/body/styles.scss
- src/components/Table/head/__test__/head.spec.js
- src/components/Table/head/header.js
- src/components/Table/head/index.js
- src/components/Table/head/styles.css
- src/components/Table/head/styles.scss
- src/components/Table/index.js
- src/components/Table/readme.md
- src/components/Table/styles.css
- src/components/Table/styles.scss
> feat: added table sorting

- .eslintrc.json
- src/components/Breadcrumbs/__test__/breadcrumbs.spec.js
- src/components/Button/__test__/button.spec.js
- src/components/CarouselCard/index.js
- src/components/CarouselCard/indicators/index.js
- src/components/Pagination/pageButtons.js
- src/components/ProgressBar/index.js
- src/components/Sidebar/context.js
- src/components/SidebarItem/__test__/sidebarItem.spec.js
- src/components/Table/__test__/table.spec.js
- src/components/Table/head/__test__/head.spec.js
- src/components/Table/head/header.js
- src/components/Table/head/index.js
- src/components/Table/index.js
- src/components/Table/readme.md
- src/components/Table/styles.css
- src/components/Table/styles.scss
- src/components/Textarea/label.js
> feat: added fixed header to the table

- src/components/Table/__test__/table.spec.js
- src/components/Table/helpers/rows/computeUniqueRowKey.js
- src/components/Table/helpers/selector/__test__/getSelectedRowKeysFromSelectedRows.spec.js
- src/components/Table/helpers/selector/getSelectedRowKeys.js
- src/components/Table/helpers/selector/getSelectedRowKeysFromSelectedRows.js
- src/components/Table/helpers/selector/index.js
- src/components/Table/helpers/selector/isDisabledRow.js
- src/components/Table/index.js
fix: #762 
- keep selected row state when data changes and keep sync with onRowSelection in Table component
> fix: keep selected row state when data changes in Table component

- src/components/Calendar/styles.css
- src/components/Calendar/styles.scss
fix: #771
- fix styles when the day is selected in Calendar component
> styles: when selcted day styles in calendar

- src/components/Lookup/__test__/lookup.spec.js
- src/components/Lookup/index.js
fix: #773 
- change onBlur and onFocus to not send search input native event
> fix: fix onFocus and onBlur events in Lookup

- src/components/Lookup/__test__/rightElement.spec.js
- src/components/Lookup/index.js
- src/components/Lookup/rightElement.js
feat: #775 
- add `searchIcon` prop to make component more customizable
> feat: add searchIcon prop to lookup component

- src/components/Table/__test__/table.spec.js
- src/components/Table/helpers/rows/__test__/getRowSelectionInputType.spec.js
- src/components/Table/helpers/rows/getRowSelectionInputType.js
- src/components/Table/helpers/rows/getRows.js
fix: #784 
- use checkbox when only one row
> fix: use checkbox when only one row

- src/components/Input/index.js
- src/components/Input/inputBase/index.js
- src/components/Input/readme.md
fix: #814 
- add debounce prop to input type search
> feat: add debounce prop to input type search

- src/components/Input/index.js
- src/components/Input/inputBase/index.js
- src/components/Input/readme.md
- remove debounce in input type search
> fix: remove debounce in input type search

- src/components/Lookup/index.js
- src/components/Lookup/options/index.js
- src/components/Lookup/options/styles.css
- src/components/Lookup/options/styles.scss
- src/components/Lookup/styles.css
- src/components/Lookup/styles.scss
- src/components/RadioGroup/styles.css
- src/components/RadioGroup/styles.scss
fix: #821 
- add prop size to the `lookup` component
> feat: add prop size to Lookup component

- integration/specs/Lookup/lookup-3.spec.js
- src/components/Lookup/helpers/isOptionVisible.js
- src/components/Lookup/index.js
- src/components/Lookup/options/__test__/options.spec.js
- src/components/Lookup/readme.md
- fix keyboard navigation in Lookup when use other size than medium
> fix: keyboard navigation in Lookup when use other size than medium

- src/components/GoogleAddressLookup/component.js
- remove GoogleAddressLookup focus
> fix: remove galookup focus

- src/components/PrimitiveMenu/index.js
fix: #
- call stopPropagation when toggle menu in PrimitiveMenu
> fix: call stopPropagation when toggle menu in PrimitiveMenu

- src/components/PrimitiveMenu/index.js
- remove stop propagation in primitive menu
> fix: remove stop propagation in primitive menu

- src/components/RadioButtonGroup/index.js
fix: #
- fix issue when options prop is changed
- fix error when options prop is changes and value prop has value
> fix: update ref when options prop are changed in RadioButtonGroup

- src/components/ImportRecordsFlow/index.js
- reset ImportRecordsFlow state when close the modal
> fix: reset ImportRecordsFlow state when close the modal

- .circleci/config.yml
- README.md
> chore: change coveralls badge to use nexxtway

- src/components/TimePicker/styles.scss
> fix: placeholder common-mixin in TimePicker

- library/pages/GettingStartedPage/index.js
- styleguide.config.js
> fix: keep sync in installation page title with react version used

- src/components/Lookup/options/__test__/options.spec.js
- src/components/Lookup/options/index.js
> fix: lookup dropdown when click

- src/components/Notification/__test__/notification.spec.js
- src/components/Notification/index.js
Hello! This is my first PR adding a small feature to your awesome project. Thanks.
- Add `hideCloseButton` props to `Notification` component, which may be useful in cases that we want to make the component stay on the screen.
> feat: add hideCloseButton to Notification component

- src/components/GoogleAddressLookup/component.js
fix: #788 
- make the first google option selected by default in the GoogleAddressLookup component
> fix: make the first google option selected by default

- src/components/ActivityTimeline/__test__/activityTimeline.spec.js
- src/components/ActivityTimeline/index.js
- src/components/ActivityTimeline/styled/container.js
- src/components/ActivityTimeline/styles.css
- src/components/ActivityTimeline/styles.scss
#950 
- Migrate ActivityTimeline to styled-components
> refactor: migrate ActivityTimeline styled components

- src/components/VisualPicker/__test__/visualPicker.a11y.spec.js
- src/components/VisualPickerOptionFooter/index.js
#962 
- Improve accessibility test on VisualPickerOption when label or description is not passed.
> test: improve accessibility test on VisualPickerOption

- src/components/Modal/__test__/modal.spec.js
- src/components/Modal/index.d.ts
- src/components/Modal/index.js
feat: add hideCloseButton prop to modal component
- Added to modal component a new optional prop called hideCloseButton, this allows to control whether the component for close the modal should render or not
- The necessary tests have been added
Issue related #1108 
> feat: add hideCloseButton prop to modal component

- src/components/GoogleAddressLookup/index.d.ts
- src/components/types.d.ts
fix: # 1176
- fix style type and import MouseEvent in GoogleAddressLookup declaration file
> fix: style type and import MouseEvent

- .eslintrc.json
fix: #1183 
- No checking of end of lines in Windows OS
> fix: end of lines issue in Windows OS

- .eslintrc.json
#848 
- Add an EsLint rule to complains about defaultProps that are not defined in PropTypes
> chore: add eslint rule to match default props and prop types

- src/components/DatePicker/index.js
fix: #1277 
- fix warning 'Function components cannot be given refs.' on DatePicker component
> fix: warning "Function components cannot be given refs." on DatePicker component

- src/components/Table/helpers/columns/__test__/isNotSameColumns.spec.js
- src/components/Table/helpers/columns/isNotSameColumns.js
fix: #1317
- Fixed action type column when children are changed
> fix: fixed action type column

- src/components/AvatarGroup/index.js
fix: #1352
- fix prop icon on the app in AvatarGroup
> fix: prop icon on AvatarGroup

- src/components/ProgressBar/styled/bar.js
- src/components/ProgressBar/styled/container.js
fix: add background alpha to progressBar component elements
--
* alpha added to background container 0.7
* alpha added to bar 0.7
> fix: add background alpha to progressBar component elements

- src/components/Table/body/styled/actionCell.js
- src/components/Table/body/styled/cellContent.js
- src/components/Table/body/styled/checkboxContainer.js
- src/components/Table/body/styled/emptyContainer.js
- src/components/Table/body/styled/loadingCell.js
- src/components/Table/head/styled/wrapper.js
fix: margin global styles are moving the margins of table component when Application wrapper is not used.
problem: when no box-sizing is added under th > div and td > div, they move the cells.
* **th > div** and **td > div** needed "box-sizing: border-box" attributes
* updated direct components under **th** and **td** wrappers
> fix: margins global styles on table component when

- src/components/Chart/__test__/chart.a11y.spec.js
- src/components/Chart/__test__/chart.spec.js
- src/components/Chart/__test__/resolveOptions.spec.js
- src/components/Chart/index.js
- src/components/Chart/resolveOptions.js
fix: #1378
- feat: add theme support for `Chart` and `Dataset` components
> feat: add theme support for `Chart` and `Dataset` components

- src/styles/helpers/__test__/attachThemeAttrs.spec.js
fix: #1329
attachThemeAttrs
- should return a merge object with props and default themes values when props.theme.rainbow is empty
- should return a merge object with props and props.theme.rainbow when props.theme.rainbow was passed
> feat: add test for `attachThemeAttrs` function

- src/components/Table/body/styled/cellContent.js
feat: add flexible table column height
* height: 42px updated to min-height: 42px
> feat: add flexible table column height

- src/components/Column/index.d.ts
fix: #1427 
- add generics to ColumnProps
> fix: type inference in column props

- src/components/ImportRecordsFlow/stepTwo/styled/dropImg.js
- src/components/ImportRecordsFlow/stepTwo/styled/dropText.js
- src/components/ImportRecordsFlow/stepTwo/styled/dropTitle.js
fix: #1440
- fix attachThemeAttrs import path
> fix: importRecordsFlow stepTwo styled import path

- src/components/Tree/readme.md
fix: #1455
- implement a real use-case when the Tree is loading
> feat: implement a real use-case when the Tree is loading

- src/components/ButtonOption/styled/text.js
> styles: fix ButtonGroupPicker size

- src/components/WeekDayPicker/index.js
fix: update to useImperativeHandle to control ref events only
> fix: update to useImperativeHandle to control ref events only

- src/components/VisualPicker/index.d.ts
- src/components/VisualPicker/index.js
- src/components/VisualPicker/readme.md
- src/components/VisualPickerOption/index.js
- src/components/VisualPickerOption/styled/content.js
- src/components/VisualPickerOption/styled/label.js
- src/components/types.d.ts
fix: #1519
- add prop size to VisualPicker component
> feat: add prop size to VisualPicker component

- src/components/Input/index.js
docs: value accepted by the autocomplete prop on Input component
-possible values for the autocomplete prop were added on Input/index.js/Input.propTypes
- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
> docs: possible values for the autocomplete prop were added on index.js

- src/components/Picklist/styled/input.js
fix: #1620 
- fix Picklist border when error and shaded is passed
> style: picklist error border when shaded

- jestMatchers/toBeFocusable.js
- package.json
- src/components/DatePicker/index.js
- yarn.lock
…nents
fix: #1634 
- fix `isFocusable` jest matcher that fail when is used on forwardRef components
> fix: fix isFocusable jest matcher

- src/components/Table/head/styled/th.js
Fix: #1167 
-Added `outline:none` in Table/head/styled/th.js .focus line 22, to prevent unexpected outlines in Safari.
> fix: remove undesired outline from table components headers

- src/components/TimePicker/__test__/ampmSelect.spec.js
- src/components/TimePicker/ampmSelect.js
- src/components/TimePicker/timeSelect.js
**Close AM / PM element by selecting**
fix: TimePicker am/pm select when clicking on the selected element #1475
- When selecting an AM/PM option, the code is sending the value update but not the signal to close. The solution for this was to modify in the "AmPmSelect" render an action of "blur" (same as close) for the moment it is clicked, that means, AM / PM has been selected.
> fix: close AM / PM element by selecting

- src/components/Tabset/__test__/tabset.spec.js
- src/components/Tabset/utils.js
fix: #1667 
- The problem was at the function "IsNotSameChildren" at utils.js (Tabset component). This function is expecting an array of objects but when a single tab is given the parameter that receives that function is an object. So, method ".some" is available for arrays but when an object is received an error occurs.
- A new check was added to make the proper comparation
> fix: tabset component with only one tab

- src/components/Chart/__test__/chart.spec.js
- src/components/Chart/chart.js
- src/components/Chart/index.js
- src/components/Chart/readme.md
- rounded styled for charts type bar 
> feat: style rounded the chart bars

- src/components/Calendar/helpers/__test__/buildNewRangeFromValue.spec.js
- src/components/Calendar/helpers/buildNewRangeFromValue.js
- src/components/Calendar/index.js
fix: #1716 
- fix the selection reset on the Calendar when clicking in a day inside the selected range
> fix: reset the selection on the Calendar when clicking in a day inside the selected range

- src/components/Breadcrumb/styled/anchor.js
- src/components/Breadcrumb/styled/button.js
- src/components/Breadcrumbs/readme.md
- src/components/Breadcrumbs/styled/ol.js
> style: add animation to the breadcrumb component

- src/components/Badge/index.d.ts
- src/components/Badge/index.js
- src/components/Badge/readme.md
- src/components/Badge/styled/container.js
fix: #1741 
- add new variants to the Badge
- add custom badge examples
> feat: adding new badge variants and examples

- src/components/PhoneInput/__tests__/phoneinput.spec.js
- src/components/PhoneInput/countriesDropdown/hooks/useKeyboardNavigation.js
fix: #1679 
- test: add test when copy and paste on the PhoneInput component to accept only number
> test: add test when copy and paste on the PhoneInput component to accept only number

- src/components/Textarea/index.d.ts
- src/components/Textarea/index.js
- src/components/Textarea/readme.md
- src/components/Textarea/styled/textareaContainer.js
> feat: add prop variant to the Textarea component

- src/components/InternalDropdown/placeholderOption.js
- src/components/InternalDropdown/styled/index.js
fix: #1778 
- Make MultiSelect header fixed when scrolling
> fix: make the MultiSelect header fixed when scrolling

- src/components/Input/index.d.ts
- src/components/Input/index.js
- src/components/Input/inputBase/__test__/input.spec.js
- src/components/Input/inputBase/index.js
- src/components/Input/readme.md
fix: #1822
- add "min" and "max" props to the Input component
- add tests
- add interactive example
> feat: add min and max props to the Input component

- src/components/FileSelector/readme.md
- remove unnecessary imports in examples
- fix indentation problem in examples
> fix: remove unnecessary imports in FileSelector component examples

- package.json
- src/components/CheckboxGroup/__test__/checkboxGroup.spec.js
- src/components/CheckboxGroup/index.d.ts
- src/components/CheckboxGroup/index.js
- src/components/CheckboxGroup/readme.md
- src/components/CheckboxGroup/styled/contentContainer.js
- src/components/RadioGroup/__test__/radioGroup.spec.js
- src/components/RadioGroup/index.d.ts
- src/components/RadioGroup/index.js
- src/components/RadioGroup/readme.md
- src/components/RadioGroup/styled/contentContainer.js
fix: #1824 
- Add optional orientation prop to radio group and checkbox group (default vertical)
- Possible values ['horizontal', 'vertical]
> feat: add `orientation` prop on the `RadioGroup` and `CheckboxGroup` components

- src/components/types.d.ts
fix: #1839 
- add ref type to BaseProps in the typescript interface
> fix: add ref type to BaseProps in the typescript interface

- package.json
- src/components/Input/index.d.ts
> fix: label alignment prop in input set as optional

- src/components/Select/__test__/select.spec.js
- src/components/Select/index.d.ts
- src/components/Select/index.js
- src/components/Select/readme.md
- src/components/Select/styled/label.js
feat(select): add prop labelAlignment to select component
closes #1844
fix: #1844 
-
> feat: add prop labelAlignment to select component

- src/components/PhoneInput/__tests__/phoneInput.a11y.spec.js
- src/components/PhoneInput/__tests__/phoneinput.spec.js
- src/components/PhoneInput/hooks/useHandleBlur.js
- src/components/PhoneInput/hooks/useHandleFocus.js
- src/components/PhoneInput/index.js
fix: #1911 
- send value in focus and blur events in PhoneInput
> fix: send value in focus and blur events in PhoneInput

- src/components/Pagination/index.d.ts
- src/components/Pagination/index.js
- src/components/Pagination/navigationButton.js
- src/components/Pagination/pageButtons.js
- src/components/Pagination/pageButtonsContainer.js
- src/components/Pagination/readme.md
- src/components/Pagination/styled/button.js
- src/components/Pagination/styled/buttonsContainer.js
- src/components/Pagination/styled/pageButton.js
> Implement shaded variant pagination component

- src/components/CounterInput/index.d.ts
- src/components/CounterInput/index.js
- src/components/CounterInput/styled/index.js
- src/components/Input/index.d.ts
- src/components/Input/index.js
- src/components/Input/styled/input.js
- src/components/MultiSelect/index.d.ts
- src/components/MultiSelect/index.js
- src/components/MultiSelect/readme.md
- src/components/MultiSelect/styled/index.js
fix: #1934 
-remove isBare from propTypes and defaultProps on CounterInput.js, Input.js and MultiSelect.js components
-add new variant 'bare on CounterInput.js, Input.js and MultiSelect.js components
-add new variant 'bare on .ts files
-use prop variant
-add new style rule considering variant==='bare' on the styled files for CounterInput.js, Input.js and MultiSelect.js
> refactor: add new variant 'bare on components using isBare

- src/components/ButtonMenu/index.d.ts
fix: #1969 
- add `label` prop to the Typescript interface on ButtonMenu component
> fix: add `label` to the Typescript interface on the ButtonMenu

- src/components/Pagination/index.js
- src/components/Pagination/readme.md
fix: #1969 
- add `label` prop to the Typescript interface on ButtonMenu component
> fix: eslint error

- src/components/Input/index.js
fix: #
-add bare to the accepted values for variant on Input.js documentation
> docs: add variant bare on the Input documentation

- src/components/Pagination/index.js
- src/components/Pagination/styled/pageButton.js
fix: #1991 
- Page Button shape fixed.
- If total pages are equal to one, then no arrow buttons are displayed.
> Fixed 🛠 Pagination Buttons 🔼🔽.

- src/components/Sidebar/readme.md
Fix typo in the name of the label Applications, in the Sidebar component examples
fix: #
-
> docs: fix label  typo in sidebar component

- src/components/Badge/index.d.ts
- src/components/Badge/index.js
- src/components/Badge/readme.md
- src/components/Badge/styled/container.js
> feat: implement size prop on badge component

- src/components/WeekDayPicker/index.d.ts
fix: #2020
- Add missing prop to index.d.ts
> fix: locale does not exist on WeekDayPicker

- src/components/ButtonGroup/index.d.ts
- src/components/ButtonGroup/index.js
- src/components/ButtonGroup/readme.md
- src/components/ButtonGroup/styled/container.js
> feat: implemented shaded variant button group

- src/components/Button/index.d.ts
- src/components/Button/index.js
fix: #2025 
-add onMouseEnter and onMouseLeave props to index.d.ts
-add PropTypes and defaultProps for onMouseEnter and onMouseLeave on index.js
-destructure onMouseEnter and onMouseLeave 
-use onMouseEnter and onMouseLeave
> feat: implement onMouseEnter and onMouseLeave props

- src/components/Calendar/day.js
- src/components/Calendar/readme.md
- src/components/Calendar/styled/dayButton.js
- src/components/Calendar/styled/rangeHighlight.js
fix: #2026 
- feat: highlight current date (today) in Calendar
> feat: highlight current date (today) in Calendar

- src/components/ProgressIndicator/__test__/progressIndicator.spec.js
- src/components/ProgressIndicator/index.d.ts
- src/components/ProgressIndicator/index.js
- src/components/ProgressIndicator/readme.md
- src/components/ProgressStep/__test__/progressStep.spec.js
- src/components/ProgressStep/index.d.ts
- src/components/ProgressStep/index.js
- src/components/ProgressStep/styled/stepButton.js
- src/components/ProgressStep/styled/stepNumberButton.js
fix: #1881
- Add variant prop to ProgressIndicator
- Add tooltip prop to ProgressStep
- Test the ProgressStep component
> feat: add variant and tooltip to ProgressIndicator

- src/components/Lookup/styled/selectedInput.js
fix: #2034
- remove wrong color when disabled
> fix: text color on GoogleAddressLookup when have a value and is disabled

- src/components/Picklist/styled/input.js
fix: #2035
- fix: styles in Picklist component when icon and readOnly is passed
> fix: styles in Picklist component when icon and readOnly is passed

- src/components/Picklist/__test__/picklist.spec.js
- src/components/Picklist/index.js
fix: #2036 
- fix: picklist when readOnly and click the label it opens the menu
> fix: picklist when readonly and click the label it opens the menu

- src/components/Button/content.js
- src/components/Button/index.d.ts
- src/components/Button/index.js
- src/components/Button/readme.md
- src/components/Button/styled/button.js
> feat: added size prop to button component

- src/components/InternalOverlay/index.js
fix: #2060
- Update `InternalOverlay` position when the content changes
-----
> fix: recalculate InternalOverlay position when content changes

- src/components/ActivityTimeline/context.js
- src/components/ActivityTimeline/helpers/getChildTimelineMarkersNodes.js
- src/components/ActivityTimeline/helpers/index.js
- src/components/ActivityTimeline/index.d.ts
- src/components/ActivityTimeline/index.js
- src/components/ActivityTimeline/readme.md
- src/components/ActivityTimeline/styled/ul.js
- src/components/TimelineMarker/__test__/timelineMarker.spec.js
- src/components/TimelineMarker/expandCollapseButton.js
- src/components/TimelineMarker/icons/downArrow.js
- src/components/TimelineMarker/icons/rightArrow.js
- src/components/TimelineMarker/index.d.ts
- src/components/TimelineMarker/index.js
- src/components/TimelineMarker/readme.md
- src/components/TimelineMarker/styled/button.js
- src/components/TimelineMarker/styled/columnLeft.js
- src/components/TimelineMarker/styled/spinner.js
- src/components/TimelineMarker/styled/spinnerContainer.js
fix: #2099 
- add `variant` prop to `ActivityTimeline` component
- add `isLoading` prop to TimelineMarker component 
> feat: improve `ActivityTimeline` and `TimelineMarker` components

- src/components/ActivityTimeline/index.d.ts
- src/components/CheckboxToggle/index.d.ts
- src/components/FileSelector/icon.js
- src/components/FileSelector/types.js
- src/libs/utils/getBrowserLocale.js
- src/libs/utils/index.js
- src/libs/utils/isServer.js
- src/styles/helpers/color/isValidColor.js
#1471 
- fix issue in next.js when adding Application component
- fix issue in next.js when adding FilseSelector component
> fix: fix application component issue in next.js

- src/components/Option/index.d.ts
fix: #2115
- Add `component` prop to Option typescript definition
-----
> fix: add `component` prop on Option type definition

- src/components/Button/index.d.ts
- src/components/types.d.ts
fix: #2107 
- fix: buttonVariant 'neutral' does not exist
> fix: buttonVariant neutral does not exist

- src/components/ButtonMenu/index.d.ts
fix: #2106 
- fix: iconPosition does not exist on ButtonMenu
> fix: iconPosition does not exist on ButtonMenu

- src/components/Calendar/index.d.ts
- src/components/DatePicker/index.d.ts
- src/components/MultiSelect/index.d.ts
fix: #2149
- Added typescript support for date ranges in Calendar, DatePicker. Added typescript support for the 'showCheckbox' prop on MultiSelect.
> fix: fixed TS definitions for Calendar, DatePicker, MultiSelect

- src/components/Tab/__test__/tab.spec.js
- src/components/Tab/index.js
> fix: set tab buttons to type button

- src/components/CarouselCard/readme.md
- src/components/CarouselImage/readme.md
fix: #2139
- Change `alternativeText` prop to 'assistiveText` in CarouselImage examples
- Change `alternativeText` prop to 'assistiveText` in CarouselCard examples
> docs: fix CarouselImage assistiveText prop in docs

- src/components/MultiSelect/index.d.ts
- src/components/MultiSelect/index.js
fix: #2184 
- add `isLoading` prop to `MultiSelect` component
> fix: add `isLoading` prop to `MultiSelect` component

- src/components/Input/label/index.d.ts
- Add type declaration to Label component
> fix: add type declaration to Label component

- src/libs/hooks/useReduxForm.d.ts
- add type declaration to useReduxForm
> fix: add type declaration to useReduxForm

- src/libs/hooks/useReduxForm.d.ts
- Fix useReduxForm type declaration
> fix: improve useReduxForm type declaration

- src/components/Tree/child.js
fix: #2178
- Pass label to checkbox in Tree child
> fix: tree child InputCheckbox error

- src/components/MarkdownOutput/__test__/markdownOutput.spec.js
- src/components/MarkdownOutput/hooks/useMarkdownToReact.js
- src/components/MarkdownOutput/index.js
- src/components/MarkdownOutput/renderers/index.js
- src/components/MarkdownOutput/renderers/styled.js
- src/components/MarkdownOutput/styled/index.js
- Added inline variant to MarkdownOutput component
> feat: add inline variant to MarkdownOutput

- src/components/MarkdownOutput/renderers/styled.js
- src/components/MarkdownOutput/styled/index.js
- Move some CSS properties to container to make it easily customizable
> fix: lift some CSS to MarkdownOutput container

- src/components/Table/body/styled/cellContainer.js
- Fix action cell overflow when table variant is listview
> fix: fix action cell overflow when table variant is listview

- src/components/Sidebar/index.d.ts
- src/components/Sidebar/index.js
- src/components/SidebarItem/__test__/sidebarItem.spec.js
- src/components/SidebarItem/index.d.ts
- src/components/SidebarItem/index.js
- src/components/SidebarItem/readme.md
- src/components/SidebarItem/styled/li.js
- add `tooltip` prop to SidebarItem
- add `hideSelectedItemIndicator` prop to Sidebar
> feat: add `tooltip` prop to SidebarItem component

- src/components/Tree/child.js
- src/components/Tree/styled/childrenContainer.js
- src/components/Tree/styled/nodeContainer.js
- src/components/Tree/styled/treeContainerUl.js
- Add left margin to Tree component
> fix: add left margin to Tree component

- src/components/InternalTooltip/styled/index.js
- src/components/SidebarItem/index.js
- Removed tooltip when a SidebarItem is focused
- Reduced tooltip fade animation to 250ms
> fix: improve Sidebar tooltip

- src/components/Tree/helpers/buildPlainListFromTree.js
- src/components/Tree/helpers/findNodeByFirstLetter.js
- src/components/Tree/hooks/useTreeNodesAsPlainList.js
> fix: node label in Tree component to accept react elements

- src/components/AccordionSection/index.js
- src/components/AccordionSection/pageObject/index.js
- Remove hard coded title from AccordionSection label
> fix: remove title from AccordionSection label

- src/components/Tree/index.d.ts
- Add `getNode` to tree interface
> fix: add `getNode` to tree interface

- src/components/AccordionSection/rightArrow.js
- Remove fixed title from RightArrow on AccordionSection component
> fix: remove fixed title from `RightArrow` on `AccordionSection`

- src/components/CheckboxToggle/index.d.ts
- src/components/CheckboxToggle/index.js
- src/components/CheckboxToggle/readme.md
- src/components/CheckboxToggle/styled/label.js
- src/components/CheckboxToggle/styled/labelContainer.js
- Add top to `labelAlignment` prop on CheckboxToggle component
> feat: add top to `labelAlignment` prop on CheckboxToggle

- src/components/InternalDropdown/helpers/searchFilter.js
- src/components/Option/index.d.ts
- src/components/Option/index.js
- src/components/PicklistOption/index.d.ts
- src/components/PicklistOption/index.js
- Fix InternalDropdown search when item label is not a string
> fix: fix InternalDropdown search when label is not a string

- src/components/PrimitiveMenu/index.js
- Add `aria-controls` to PrimitiveMenu trigger
> fix: add `aria-controls` to PrimitiveMenu trigger

- src/components/StripeCardInput/index.d.ts
- src/components/StripeCardInput/index.js
- Added id prop to StripeCardInput component
> fix: add `id` prop to StripeCardInput component

- src/components/CarouselCard/index.js
fix: #2260 
- Clear animation timeout on componentWillUnmount to avoid a memory leak
> fix: fix memory leak on CarouselCard component

- src/components/Table/head/resizeBar.js
- src/libs/outsideClick/index.js
- src/libs/scrollController/index.js
fix: #2276 
- Move all event listeners on document to the capture phase
See [here](https://es.reactjs.org/blog/2020/10/20/react-v17.html#changes-to-event-delegation) and [here](https://es.reactjs.org/blog/2020/08/10/react-v17-rc.html#fixing-potential-issues) for explanation.
> fix: move document event listeners to capture phase

- integration/specs/CheckboxGroup/checkboxGroup-1.spec.js
- integration/specs/RadioGroup/radioGroup-1.spec.js
- src/components/CheckboxGroup/checkboxList.js
- src/components/CheckboxGroup/index.d.ts
- src/components/CheckboxGroup/index.js
- src/components/CheckboxGroup/pageObject/index.js
- src/components/CheckboxGroup/readme.md
- src/components/RadioGroup/index.js
- src/components/RadioGroup/pageObject/index.js
- src/components/RadioGroup/radioItems.js
- src/components/RadioGroup/readme.md
- src/components/RadioGroup/styled/itemContainer.js
- src/components/RadioGroup/styled/itemDescription.js
- src/components/types.d.ts
- Add description prop to RadioGroup options
- Add description prop to CheckboxGroup options
> feat: add description prop to options on RadioGroup and CheckboxGroup components

- src/components/MarkdownOutput/renderers/styled.js
- src/components/MarkdownOutput/styled/index.js
- Added paddinng to the top of the MarkdownOutput component
> fix: add padding top to MarkdownOutput

- src/components/Picklist/__test__/picklist.spec.js
- src/components/Picklist/index.js
- src/libs/WindowResize/index.js
- Close Picklist when window is resized
> fix: close Picklist on viewport resize

- src/components/DatePicker/__test__/datePicker.spec.js
- src/components/DatePicker/index.d.ts
- src/components/DatePicker/index.js
- src/components/DatePicker/readme.md
- src/components/DateTimePicker/__test__/dateTimePicker.spec.js
- src/components/DateTimePicker/index.js
- src/components/DateTimePicker/readme.md
- src/components/MarkdownOutput/readme.md
fix: #2315 
- Add the icon prop to DatePicker and DateTimePicker
> feat: add the icon prop to DatePicker and DateTimePicker

- src/components/HelpText/index.js
- src/components/PrimitiveMenu/index.js
- Close ButtonMenu on scroll
- Close HelpText on scroll
- Fix Button first click not working inside HelpText tooltip
> fix: improve ButtonMenu and HelpText dropdowns

- src/components/ZoomableImage/__test__/zoomedImage.spec.js
- src/components/ZoomableImage/zoomedImage.js
- Close ZoomableImage when press Escape key
> fix: close ZoomableImage on Escape key

- src/components/ColorPicker/commons/rgba/styled.js
- Remove up and down arrows from number inputs in the ColorPicker on Firefox.
[x] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
> fix: remove arrows from number inputs on mozilla in ColorPicker

- src/components/CodeInput/index.js
- src/components/ColorInput/index.js
- src/components/PhoneInput/__tests__/phoneinput.spec.js
- src/components/PhoneInput/countriesDropdown/hooks/useKeyboardNavigation.js
- src/components/PhoneInput/countriesDropdown/index.js
- src/components/PhoneInput/countriesDropdown/styled/dropdown.js
- src/components/PhoneInput/helpers/positionResolver.js
- src/components/PhoneInput/hooks/useHandleBlur.js
- src/components/PhoneInput/hooks/useHandleCountryChange.js
- src/components/PhoneInput/hooks/useHandleFocus.js
- src/components/PhoneInput/index.js
- src/components/ZoomableImage/__test__/zoomedImage.spec.js
fix: #2327 
- Refactor PhoneInput to use InternalOverlay
> fix: refactor PhoneInput component

- src/components/ColorInput/index.js
- Close ColorInput picker on scroll
> fix: close ColorInput picker on scroll

- src/components/Column/index.d.ts
- src/components/Column/index.js
- src/components/Column/readme.md
- src/components/Table/__test__/table.spec.js
- src/components/Table/head/header.js
- src/components/Table/head/sortArrowIcon.js
- src/components/Table/head/styled/headerContainer.js
- src/components/Table/head/styled/sortArrowIcon.js
- src/components/Table/helpers/columns/__test__/getColumns.spec.js
fix: #2337 
- Added `headerAlignment` prop to Column component.
> feat: add headerAlignment prop to the Column component

- src/components/MonthlyCalendar/month.js
- Fixed MonthlyCalendar not rendering days on some project configurations
> fix: fix MonthlyCalendar not rendering days

- src/components/Column/index.js
- src/components/Column/readme.md
- src/components/Table/__test__/table.spec.js
- src/components/Table/head/header.js
- src/components/Table/head/sortArrowIcon.js
- src/components/Table/head/styled/headerContainer.js
- src/components/Table/helpers/columns/__test__/getColumns.spec.js
- Added support for headerAlignment to listview variant
> feat: add `headerAlignment` to Table listview variant

- src/components/VerticalItem/styled/anchor.js
- src/components/VerticalItem/styled/button.js
fix: #2193 
- Remove font-family from VerticalItem when active.
> fix: remove font-family from active VerticalItem

- src/components/Input/label/__test__/label.spec.js
- src/components/Input/label/index.js
- Hide RequiredAsterisk when there is no label
> fix: hide RequiredAsterisk when there is no label

- src/components/TimePicker/__test__/timePicker.spec.js
- src/components/TimePicker/index.d.ts
- src/components/TimePicker/index.js
- src/components/TimePicker/readme.md
- Added `icon` prop to TimePicker component
> feat: add the `icon` prop to TimePicker component

- src/components/Card/__test__/card.spec.js
- src/components/Card/index.d.ts
- src/components/Card/index.js
fix: #2348 
- Added `id` prop to Card component
> fix: add `id` prop to Card component

- src/components/GMap/index.js
- Updated GMap API script url to match the one used in GoogleAddressLookup.
The GoogleAddressLookup and GMap components both depends on the Maps API, loaded from a remote script using `react-async-script-loader`, but GoogleAddressLookup needs the places library (adding `&libraries=places` to the script url). This caused the URLs loaded by the components to differ, and the script to load twice.
The solution is to make the two components to load the same URL, this way `react-async-script-loader` realizes it is the same script and load only once. The downside to this approach is that when using the GMap component only, the Map API script loaded is a little bigger because it includes the places API even if it is not necessary.
> fix: update GMap script url

- src/components/CheckboxGroup/checkboxList.js
fix: #2352 
- Fixed error in console when using CheckboxGroup because `key  prop was on the wrong component.
> fix: fix CheckboxGroup console error

- src/components/InternalOverlay/helpers/__test__/resolverTopLeft.spec.js
- src/components/InternalOverlay/helpers/__test__/resolverTopRight.spec.js
- src/components/InternalOverlay/helpers/defaultPositionResolver.js
- src/components/InternalOverlay/helpers/resolverTopLeft.js
- src/components/InternalOverlay/helpers/resolverTopRight.js
- Added two new position resolvers to InternalOverlay:
- Top left: positions the overlay at the left of the trigger with top: 0, applies when it is not possible to center the overlay on one of the sides.
- Top right: same as above, but to the right of the trigger.
> feat: add new position resolvers

- src/components/InternalOverlay/index.d.ts
- Added missing `children` prop to InternalOverlay types
> fix: add `children` prop to InternalOverlay types

- src/components/DatePickerModal/index.d.ts
- Fixed DatePickerModal value types to include `Date[]`
> fix: update DatePickerModal value types

- src/components/HelpText/index.js
- Added function to HelpText to allow closing the tooltip imperatively.
> feat: add imperative `close` function to HelpText

- src/components/RadioGroup/radioItems.js
fix: #2411
- Fixed error in console when using RadioGroup because `key prop was on the wrong component.
> fix: fix RadioGroup console error

- integration/specs/Calendar/calendar-11.spec.js
- integration/specs/Calendar/calendar-5.spec.js
- integration/specs/Calendar/calendar-7.spec.js
- integration/specs/Calendar/calendar-9.spec.js
- src/components/Calendar/day.js
- src/components/Calendar/doubleCalendar/index.js
- src/components/Calendar/helpers/__test__/isInArray.spec.js
- src/components/Calendar/helpers/__test__/normalizeDates.spec.js
- src/components/Calendar/helpers/index.js
- src/components/Calendar/helpers/isInArray.js
- src/components/Calendar/helpers/normalizeDate.js
- src/components/Calendar/helpers/normalizeDates.js
- src/components/Calendar/index.d.ts
- src/components/Calendar/index.js
- src/components/Calendar/pageObject/doubleCalendar.js
- src/components/Calendar/pageObject/singleCalendar.js
- src/components/Calendar/readme.md
- src/components/Calendar/singleCalendar.js
- src/components/DatePicker/index.d.ts
- src/components/DatePicker/index.js
- src/components/DatePickerModal/index.d.ts
- src/components/DatePickerModal/index.js
- src/components/DateTimePicker/index.d.ts
- src/components/DateTimePicker/index.js
- src/components/DateTimePicker/pickerModal.js
fix: #2423 
- Added `disabledDays` prop to Calendar, DatePicker, DateTimePicker and its modals
> feat: add `disabledDays` prop to Calendar

- src/components/InternalDropdown/index.js
> fix: picklist issue

- src/components/Table/body/styled/cell.js
- src/components/Table/body/styled/row.js
- src/components/Table/readme.md
> fix: cell bug in firefox

- src/components/Button/buttonContent.js
- src/components/InternalOverlay/index.js
> fix: prop types

- src/components/Input/label/labelText.js
> fix: add missing semicolon to labelText styles

- src/components/Button/styled/button.js
fix: #2456
- fix: disabled button when click on it
> fix: disabled button when click on it

- src/components/Dataset/index.d.ts
fix: #2460 
- feat: add extra types to dataset component
> feat: add extra types to dataset component

- src/components/Table/index.d.ts
fix: #2454
- fix: types in onSort prop of the Table to be more strict (nextSortdirection must be the same as the prop sortDirection asc | desc)
> fix: types in onSort prop of the table to be more strict

- src/components/Chart/index.d.ts
fix: #2458
- feat: add options declaration type to chart component
> feat: add options declaration type to chart component

- src/components/CurrencyInput/helpers/clearValue.js
- src/components/CurrencyInput/helpers/countCharacters.js
- src/components/CurrencyInput/helpers/formatCurrency.js
- src/components/CurrencyInput/helpers/formatInteger.js
- src/components/CurrencyInput/helpers/getSeparator.js
- src/components/CurrencyInput/helpers/index.js
- src/components/CurrencyInput/helpers/isValidStringNumber.js
- src/components/CurrencyInput/helpers/normalizeValue.js
- src/components/CurrencyInput/hooks/index.js
- src/components/CurrencyInput/hooks/useDecimalSeparator.js
- src/components/CurrencyInput/hooks/useGroupSeparator.js
- src/components/CurrencyInput/hooks/useOptions.js
- src/components/CurrencyInput/index.d.ts
- src/components/CurrencyInput/index.js
- src/components/CurrencyInput/readme.md
- src/index.d.ts
- src/index.js
fix: #2467 
- feat: add currency input component
> feat: add currency input component

- src/components/HelpText/index.js
- src/components/HelpText/styled/index.js
fix: #2469 
- fix-improve-shadow-in-the-help-text-component
> fix: improve shadow in the help text component

- src/components/Button/index.js
- src/components/Input/styled/input.js
- src/components/StrongPasswordInput/index.d.ts
- src/components/StrongPasswordInput/index.js
fix: #2476 
- feat: add strong password input prop size
> feat: add strong password input prop size

- src/components/CurrencyInput/index.d.ts
- src/components/CurrencyInput/index.js
- src/components/PercentInput/index.d.ts
- src/components/PercentInput/index.js
fix: #2475 
- feat: add prop valueAlignment to currencyInput and percentInput
> feat: add prop valueAlignment to currencyInput and percentInput

- src/components/Button/content.js
- src/components/Button/index.d.ts
- src/components/Button/index.js
- src/components/Button/readme.md
- src/components/Button/styled/button.js
- src/styles/borderRadius.js
fix: #2491 
-add borderRadius prop to Button component
> feat: add border radius prop to button

- package.json
- setupTests.js
- src/components/CurrencyInput/__test__/currencyInput.spec.js
- src/components/CurrencyInput/helpers/formatCurrency.js
- src/components/CurrencyInput/helpers/index.js
- src/components/CurrencyInput/helpers/isValidCurrencyValue.js
- src/components/CurrencyInput/helpers/isValidNumberValue.js
- src/components/CurrencyInput/helpers/normalizeValue.js
- yarn.lock
fix: #2468 
- tests: add unit tests to currency input
- feat: add @testing-library/react for unit tests
- feat: add @testing-library/jest-dom for new jest checkup
- feat: add @testing-library/user-event for new event simulation
- feat: add @rainbow-modules/validation for validation functions
> tests: add unit tests to currency input

- src/components/Button/readme.md
- src/components/ButtonIcon/index.d.ts
- src/components/ButtonIcon/index.js
- src/components/ButtonIcon/readme.md
- src/components/ButtonIcon/styled/button.js
fix: #2494
-Add borderRadius prop to ButtonIcon component
> feat: add border radius radius prop to button icon

- src/components/RadioButtonGroup/index.d.ts
- src/components/RadioButtonGroup/index.js
- src/components/RadioButtonGroup/marker.js
- src/components/RadioButtonGroup/readme.md
- src/components/RadioButtonGroup/styled/buttonItemsContainer.js
- src/components/RadioButtonGroup/styled/marker.js
fix: #2495 
-Add border radius to radio button group
> feat: add border radius to radio button group

- src/components/Picklist/index.js
> fix: make picklist responsive for mobile when search is enabled

- src/components/ButtonGroup/index.d.ts
- src/components/ButtonGroup/index.js
- src/components/ButtonGroup/readme.md
- src/components/ButtonGroup/styled/container.js
fix: #2498 
-add borderRadius prop to ButtonGroup component
> Add border radius to button group

- src/components/ButtonGroupPicker/__test__/buttonGroupPicker.spec.js
- src/components/CodeInput/__test__/codeInput.spec.js
- src/components/CounterInput/index.js
- src/components/CurrencyInput/index.js
- src/components/FileSelector/__test__/fileSelector.spec.js
- src/components/Input/inputBase/__test__/input.spec.js
- src/components/Input/inputBase/index.js
- src/components/Input/label/index.d.ts
- src/components/Input/label/index.js
- src/components/Input/label/labelText.js
- src/components/Input/pickerInput/__test__/input.spec.js
- src/components/Input/pickerInput/index.js
- src/components/Lookup/__test__/lookup.spec.js
- src/components/Lookup/index.js
- src/components/PercentInput/index.js
- src/components/PhoneInput/index.js
- src/components/Picklist/index.js
- src/components/Select/__test__/select.spec.js
- src/components/Select/index.js
- src/components/StrongPasswordInput/__test__/strongPasswordInput.spec.js
- src/components/StrongPasswordInput/index.js
- src/components/Textarea/__test__/textarea.spec.js
- src/components/VisualPicker/__test__/visualPicker.spec.js
- src/components/WeekDayPicker/__test__/weekDayPicker.spec.js
fix: #2507 
-fix: make the label on the inputable components more bigger when the size='large'
> fix: make the label on the inputable components more bigger when the size=large

- src/components/ButtonIcon/styled/button.js
fix: #2584 
- fix: disabled button icon makes an animation when clicked
> fix: disabled button icon makes an animation when clicked

- src/components/ImportRecordsFlow/stepThree/styled/databaseFieldCell.js
fix: #2601
-add padding to the first cell of the third step in import record flow component
> fix: add padding to the first cell of the third step in import record flow component

- src/components/Textarea/styled/textarea.js
> fix: error styles on textarea

- src/components/CounterInput/index.js
fix: Fix a typo in the default props of the CounterInput component.
- Fix a typo in the default props of the CounterInput component
> fix: fix typo in default props of CounterInput component

- src/components/Input/index.d.ts
- src/components/Input/index.js
- src/components/Input/inputBase/index.js
fix: #
- add prop `step` to Input component
> fix: add `step` to props to `Input` component

- src/components/Modal/index.js
fix: #2625 
- fix borderRadius styles on Modal's closeButton
> fix: borderRadius styles on Modal's closeButton

- src/components/Calendar/day.js
fix: #
- set type="button" to calendar day
> fix: form submit when click a day in Calendar component
